package com.fliad.viid.modular.cascadeplatform.domain;

import lombok.Data;

import java.util.List;

/**
 * 案事件标注人脸对象（参照文档附录A.11.1，案事件标注场景下的人脸扩展信息）
 */
@Data
public class CaseAnnotatedFace {
    // 1. 人脸标识（必选）
    private String FaceID;
    // 2. 信息分类（人工采集/自动采集，必选）
    private String InfoKind;
    // 3. 来源图像信息标识（可选）
    private String SourceID;
    // 4. 设备编码（自动采集必选，可选）
    private String DeviceID;
    // 5. 人脸区域左上角X坐标（自动采集必选，可选）
    private Integer LeftTopX;
    // 6. 人脸区域左上角Y坐标（自动采集必选，可选）
    private Integer LeftTopY;
    // 7. 人脸区域右下角X坐标（自动采集必选，可选）
    private Integer RightBtmX;
    // 8. 人脸区域右下角Y坐标（自动采集必选，可选）
    private Integer RightBtmY;
    // 9. 位置标记时间（可选）
    private String LocationMarkTime;
    // 10. 人脸出现时间（人工采集时有效，可选）
    private String FaceAppearTime;
    // 11. 人脸消失时间（可选）
    private String FaceDisAppearTime;
    // 12. 证件种类（已知身份人脸数据必选，可选）
    private String IDType;
    // 13. 证件号码（已知身份人脸数据必选，可选）
    private String IDNumber;
    // 14. 姓名（已知身份人脸数据必选，可选）
    private String Name;
    // 15. 曾用名（可选）
    private String UsedName;
    // 16. 绰号（可选）
    private String Alias;
    // 17. 性别代码（已知身份人脸数据必选，可选）
    private String GenderCode;
    // 18. 年龄上限（最大可能年龄，可选）
    private Integer AgeUpLimit;
    // 19. 年龄下限（最小可能年龄，可选）
    private Integer AgeLowerLimit;
    // 20. 民族代码（中国各民族罗马字母拼写法和代码，已知身份人脸数据必选，可选）
    private String EthicCode;
    // 21. 国籍代码（世界各国和地区名称代码，可选）
    private String NationalityCode;
    // 22. 籍贯省市县代码（可选）
    private String NativeCityCode;
    // 23. 居住地行政区划（可选）
    private String ResidenceAdminDivision;
    // 24. 汉语口音代码（汉语口音编码规则，可选）
    private String ChineseAccentCode;
    // 25. 职业类别代码（职业分类与代码，不含“—”，可选）
    private String JobCategoryCode;
    // 26. 同行人脸数（被标注人脸的同行人脸数，可选）
    private Integer AccompanyNumber;
    // 27. 肤色（可选）
    private String SkinColor;
    // 28. 发型（可选）
    private String HairStyle;
    // 29. 发色（可选）
    private String HairColor;
    // 30. 脸型（可选）
    private String FaceStyle;
    // 31. 脸部特征（可选）
    private String FacialFeature;
    // 32. 体貌特征（可选）
    private String PhysicalFeature;
    // 33. 口罩颜色（可选）
    private String RespiratorColor;
    // 34. 帽子款式（可选）
    private String CapStyle;
    // 35. 帽子颜色（可选）
    private String CapColor;
    // 36. 眼镜款式（可选）
    private String GlassStyle;
    // 37. 眼镜颜色（可选）
    private String GlassColor;
    // 38. 是否驾驶员（0:否，1:是，2:不确定，可选）
    private Integer IsDriver;
    // 39. 是否涉外人员（0:否，1:是，2:不确定，可选）
    private Integer IsForeigner;
    // 40. 护照证件种类（可选）
    private String PassportType;
    // 41. 出入境人员类别代码（出入境人员分类代码，可选）
    private String ImmigrantTypeCode;
    // 42. 是否涉恐人员（0:否，1:是，2:不确定，可选）
    private Integer IsSuspectedTerrorist;
    // 43. 涉恐人员编号（可选）
    private String SuspectedTerroristNumber;
    // 44. 是否涉案人员（0:否，1:是，2:不确定，可选）
    private Integer IsCriminalInvolved;
    // 45. 涉案人员专长代码（可选）
    private String CriminalInvolvedSpecilisationCode;
    // 46. 体表特殊标记（可选）
    private String BodySpeciallMark;
    // 47. 作案手段（可选）
    private String CrimeMethod;
    // 48. 作案特点代码（可选）
    private String CrimeCharacterCode;
    // 49. 在逃人员编号（可选）
    private String EscapedCriminalNumber;
    // 50. 是否在押人员（0:否，1:是，2:不确定，人工采集必填，可选）
    private Integer IsDetainees;
    // 51. 看守所编码（可选）
    private String DetentionHouseCode;
    // 52. 在押人员身份（参照文档附录B，可选）
    private String DetaineesIdentity;
    // 53. 在押人员特殊身份（可选）
    private String DetaineesSpecialIdentity;
    // 54. 成员类型代码（可选）
    private String MemberTypeCode;
    // 55. 是否被害人（0:否，1:是，2:不确定，可选）
    private Integer IsVictim;
    // 56. 被害人种类（可选）
    private String VictimType;
    // 57. 受伤害程度（可选）
    private String InjuredDegree;
    // 58. 尸体状况代码（可选）
    private String CorpseConditionCode;
    // 59. 是否可疑人（0:否，1:是，2:不确定，可选）
    private Integer IsSuspiciousPerson;
    // 60. 姿态分布（1:平视，2:微仰，3:微俯，4:左微侧脸，5:左斜侧脸，6:左全侧脸，7:右微侧脸，8:右斜侧脸，9:右全侧脸，可选）
    private Integer Attitude;
    // 61. 人脸相似度（取值范围[0,1]，可选）
    private Double SimilarityDegree;
    // 62. 眉型（多个特征用英文半角分号“;”分隔，可选）
    private String EyebrowStyle;
    // 63. 鼻型（多个特征用英文半角分号“;”分隔，可选）
    private String NoseStyle;
    // 64. 胡型（可选）
    private String MustacheStyle;
    // 65. 嘴唇（多个特征用英文半角分号“;”分隔，可选）
    private String LipStyle;
    // 66. 皱纹眼袋（多个特征用英文半角分号“;”分隔，可选）
    private String WrinklePouch;
    // 67. 痤疮色斑（多个特征用英文半角分号“;”分隔，可选）
    private String AcneStain;
    // 68. 黑痣胎记（多个特征用英文半角分号“;”分隔，可选）
    private String FreckleBirthmark;
    // 69. 疤痕酒窝（多个特征用英文半角分号“;”分隔，可选）
    private String ScarDimple;
    // 70. 其他特征（多个特征用英文半角分号“;”分隔，可选）
    private String OtherFeature;
    // 71. 图像列表（包含0或多个子图像对象，可选）
    private List<SubImageInfo> SubImageList;
    // 72. 拍摄时间（自动采集时必填，可选）
    private String ShotTime;
    // 73. 特征值列表（人脸特征值列表，可选）
    private List<FeatureInfo> FeatureList;
    // 74. 归属分类标签标识（可选）
    private String TabID;
}
