
CREATE TABLE HIKVISION_CAMERA(
  ID VARCHAR(20) NOT NULL    COMMENT '主键',
  DEVICE_ID VARCHAR(64) NULL    COMMENT '设备编号',
  NAME VARCHAR(128) NOT NULL    COMMENT '设备名称',
  IP_ADDR VARCHAR(64) NOT NULL    COMMENT '设备IP地址',
  PORT INTEGER NOT NULL    COMMENT '端口号',
  USERNAME VARCHAR(64) NOT NULL    COMMENT '用户名',
  PASSWORD VARCHAR(128) NOT NULL    COMMENT '密码',
  ENABLE_STATUS BOOLEAN default 1  NOT NULL    COMMENT '启用状态：1=启用，0=禁用',
  ONLINE_STATUS BOOLEAN default 0  NOT NULL    COMMENT '在线状态：1=在线，0=离线',
  CREATE_TIME DATETIME NOT NULL    COMMENT '创建时间',
  UPDATE_TIME DATETIME NOT NULL    COMMENT '更新时间',
  constraint IDX_HIKVISION_CAMERA_NAME unique (NAME),
  constraint PK_HIKVISION_CAMERA primary key (ID)
);

CREATE TABLE VEHICLE_TRAFFIC_RECORD(
  ID VARCHAR(20) NOT NULL    COMMENT '主键',
  KKBH VARCHAR(50) NULL    COMMENT '卡口编号，符合GA/T 16.31与GA/T 543.10要求',
  FXLX VARCHAR(20) NULL    COMMENT '方向类型',
  CDH VARCHAR(10) NULL    COMMENT '车道号',
  GCSJ DATETIME NULL    COMMENT '过车时间，格式yyyy-mm-dd hh24:mi:ss',
  WFDM VARCHAR(20) NULL    COMMENT '违法行为，符合GA/T 16.31与GA/T 543.5要求',
  HPHM VARCHAR(20) NOT NULL    COMMENT '号牌号码，符合GA/T 543.5要求，无牌等用"-"表示',
  HPZL VARCHAR(2) NOT NULL    COMMENT '号牌种类，符合GA/T 16.7与GA/T 543.5要求：01-大型汽车,02-小型汽车,...,99-其他号牌',
  HPYS TINYINT NOT NULL    COMMENT '号牌颜色，符合GB 1.1-2009：0-白色,1-黄色,2-蓝色,3-黑色,4-绿色,5-未识别,9-其他颜色',
  FZHPHM VARCHAR(20) NULL    COMMENT '辅助号牌号码，无牌等用"-"表示',
  FZHPZL VARCHAR(2) NULL    COMMENT '辅助号牌种类，符合GA/T 16.7与GA/T 543.5要求',
  FZHPYS TINYINT NULL    COMMENT '辅助号牌颜色：0-白色,1-黄色,2-蓝色,3-黑色,4-绿色,5-未识别,9-其他颜色',
  CLLX VARCHAR(20) NULL    COMMENT '车辆类型，符合GA/T 16.4与GA/T 543.5要求',
  CWKC VARCHAR(5) NULL    COMMENT '车外廓长，单位厘米，最长5位',
  CLPP VARCHAR(50) NULL    COMMENT '车辆品牌，符合GA/T 543.10要求',
  CSYS VARCHAR(2) NULL    COMMENT '车身颜色，符合GA/T 16.8与GA/T 543.5：A-白,B-灰,C-黄,D-粉,E-红,F-紫,G-绿,H-蓝,I-棕,J-黑',
  HPKXD TINYINT NULL    COMMENT '号牌识别可信度，0~100%',
  MWHPKXD VARCHAR(200) NULL    COMMENT '每位号牌识别可信度，格式如"苏-80,B-90,..."',
  CXKXD TINYINT NULL    COMMENT '车型识别可信度，0~100%',
  PPKXD TINYINT NULL    COMMENT '品牌识别可信度，0~100%',
  XWTZ VARCHAR(50) NULL    COMMENT '行为特征，1-不系安全带;2-拨打电话;...多个用分号分隔',
  TPLJ VARCHAR(255) NULL    COMMENT '图片路径',
  TP1 VARCHAR(255) NULL    COMMENT '通行图片1',
  TP2 VARCHAR(255) NULL    COMMENT '通行图片2',
  TP3 VARCHAR(255) NULL    COMMENT '通行图片3',
  TZTP VARCHAR(255) NULL    COMMENT '特征图片',
  JSRTP VARCHAR(255) NULL    COMMENT '驾驶人图片',
  CLSD INTEGER NULL    COMMENT '车辆速度，单位km/h',
  TID VARCHAR(50) NULL    COMMENT 'rfid标签芯片识别号',
  ZKRS INTEGER NULL    COMMENT '载客人数',
  CID VARCHAR(50) NULL    COMMENT 'rfid标识卡号码',
  SXJBH VARCHAR(50) NULL    COMMENT '摄像机设备编号',
  constraint PK_VEHICLE_TRAFFIC_RECORD primary key (ID)
);


   ALTER TABLE HIKVISION_CAMERA COMMENT '海康布防表';
                
   ALTER TABLE VEHICLE_TRAFFIC_RECORD COMMENT '车辆通行记录信息表';
                
