
CREATE TABLE DEV_CONFIG(
  ID VARCHAR(20) NOT NULL    COMMENT 'Id',
  CONFIG_KEY VARCHAR(255) NULL    COMMENT '配置键',
  CONFIG_VALUE LONGTEXT NULL    COMMENT '配置值',
  CATEGORY VARCHAR(255) NULL    COMMENT '分类',
  REMARK VARCHAR(255) NULL    COMMENT '备注',
  SORT_CODE INTEGER NULL    COMMENT '排序码',
  EXT_JSON LONGTEXT NULL    COMMENT '扩展信息',
  DELETE_FLAG VARCHAR(255) NULL    COMMENT '删除标志',
  CREATE_TIME DATETIME NULL    COMMENT '创建时间',
  CREATE_USER VARCHAR(20) NULL    COMMENT '创建用户',
  UPDATE_TIME DATETIME NULL    COMMENT '修改时间',
  UPDATE_USER VARCHAR(20) NULL    COMMENT '修改用户',
  constraint PK_DEV_CONFIG primary key (ID)
);

CREATE TABLE DEV_DICT(
  ID VARCHAR(20) NOT NULL    COMMENT 'Id',
  PARENT_ID VARCHAR(20) NULL    COMMENT '父id',
  DICT_LABEL VARCHAR(255) NULL    COMMENT '字典文字',
  DICT_VALUE VARCHAR(255) NULL    COMMENT '字典值',
  CATEGORY VARCHAR(255) NULL    COMMENT '分类',
  SORT_CODE INTEGER NULL    COMMENT '排序码',
  EXT_JSON LONGTEXT NULL    COMMENT '扩展信息',
  DELETE_FLAG VARCHAR(255) NULL    COMMENT '删除标志',
  CREATE_TIME DATETIME NULL    COMMENT '创建时间',
  CREATE_USER VARCHAR(20) NULL    COMMENT '创建用户',
  UPDATE_TIME DATETIME NULL    COMMENT '修改时间',
  UPDATE_USER VARCHAR(20) NULL    COMMENT '修改用户',
  constraint PK_DEV_DICT primary key (ID)
);

CREATE TABLE DEV_EMAIL(
  ID VARCHAR(20) NOT NULL    COMMENT 'Id',
  ENGINE VARCHAR(255) NULL    COMMENT '邮件引擎',
  SEND_ACCOUNT VARCHAR(255) NULL    COMMENT '发件人邮箱',
  SEND_USER VARCHAR(255) NULL    COMMENT '发件人昵称',
  RECEIVE_ACCOUNTS TEXT NULL    COMMENT '接收人',
  SUBJECT TEXT NULL    COMMENT '邮件主题',
  CONTENT LONGTEXT NULL    COMMENT '邮件正文',
  TAG_NAME VARCHAR(255) NULL    COMMENT '标签名',
  TEMPLATE_NAME TEXT NULL    COMMENT '模板名',
  TEMPLATE_PARAM TEXT NULL    COMMENT '发送参数',
  RECEIPT_INFO LONGTEXT NULL    COMMENT '回执信息',
  EXT_JSON LONGTEXT NULL    COMMENT '扩展信息',
  DELETE_FLAG VARCHAR(255) NULL    COMMENT '删除标志',
  CREATE_TIME DATETIME NULL    COMMENT '创建时间',
  CREATE_USER VARCHAR(20) NULL    COMMENT '创建用户',
  UPDATE_TIME DATETIME NULL    COMMENT '修改时间',
  UPDATE_USER VARCHAR(20) NULL    COMMENT '修改用户',
  constraint PK_DEV_EMAIL primary key (ID)
);

CREATE TABLE DEV_FILE(
  ID VARCHAR(20) NOT NULL    COMMENT 'Id',
  ENGINE VARCHAR(255) NULL    COMMENT '存储引擎',
  BUCKET VARCHAR(255) NULL    COMMENT '存储桶',
  NAME TEXT NULL    COMMENT '文件名称',
  SUFFIX VARCHAR(255) NULL    COMMENT '文件后缀',
  SIZE_KB BIGINT NULL    COMMENT '文件大小kb',
  SIZE_INFO VARCHAR(255) NULL    COMMENT '文件大小（格式化后）',
  OBJ_NAME TEXT NULL    COMMENT '文件的对象名（唯一名称）',
  STORAGE_PATH TEXT NULL    COMMENT '文件存储路径',
  DOWNLOAD_PATH TEXT NULL    COMMENT '文件下载路径',
  THUMBNAIL LONGTEXT NULL    COMMENT '图片缩略图',
  EXT_JSON LONGTEXT NULL    COMMENT '扩展信息',
  DELETE_FLAG VARCHAR(255) NULL    COMMENT '删除标志',
  CREATE_TIME DATETIME NULL    COMMENT '创建时间',
  CREATE_USER VARCHAR(20) NULL    COMMENT '创建用户',
  UPDATE_TIME DATETIME NULL    COMMENT '修改时间',
  UPDATE_USER VARCHAR(20) NULL    COMMENT '修改用户',
  constraint PK_DEV_FILE primary key (ID)
);

CREATE TABLE DEV_JOB(
  ID VARCHAR(20) NOT NULL    COMMENT 'Id',
  NAME VARCHAR(255) NULL    COMMENT '名称',
  CODE VARCHAR(255) NULL    COMMENT '编码',
  CATEGORY VARCHAR(255) NULL    COMMENT '分类',
  ACTION_CLASS VARCHAR(255) NULL    COMMENT '任务类名',
  CRON_EXPRESSION VARCHAR(255) NULL    COMMENT 'cron表达式',
  JOB_STATUS VARCHAR(255) NULL    COMMENT '任务状态',
  SORT_CODE INTEGER NULL    COMMENT '排序码',
  EXT_JSON LONGTEXT NULL    COMMENT '扩展信息',
  DELETE_FLAG VARCHAR(255) NULL    COMMENT '删除标志',
  CREATE_TIME DATETIME NULL    COMMENT '创建时间',
  CREATE_USER VARCHAR(20) NULL    COMMENT '创建用户',
  UPDATE_TIME DATETIME NULL    COMMENT '修改时间',
  UPDATE_USER VARCHAR(20) NULL    COMMENT '修改用户',
  constraint PK_DEV_JOB primary key (ID)
);

CREATE TABLE DEV_LOG(
  ID VARCHAR(20) NOT NULL    COMMENT '主键',
  CATEGORY VARCHAR(255) NULL    COMMENT '日志分类',
  NAME VARCHAR(255) NULL    COMMENT '日志名称',
  EXE_STATUS VARCHAR(255) NULL    COMMENT '执行状态',
  EXE_MESSAGE LONGTEXT NULL    COMMENT '具体消息',
  OP_IP VARCHAR(255) NULL    COMMENT '操作ip',
  OP_ADDRESS VARCHAR(255) NULL    COMMENT '操作地址',
  OP_BROWSER VARCHAR(255) NULL    COMMENT '操作浏览器',
  OP_OS VARCHAR(255) NULL    COMMENT '操作系统',
  CLASS_NAME VARCHAR(255) NULL    COMMENT '类名称',
  METHOD_NAME VARCHAR(255) NULL    COMMENT '方法名称',
  REQ_METHOD VARCHAR(255) NULL    COMMENT '请求方式',
  REQ_URL LONGTEXT NULL    COMMENT '请求地址',
  PARAM_JSON LONGTEXT NULL    COMMENT '请求参数',
  RESULT_JSON LONGTEXT NULL    COMMENT '返回结果',
  OP_TIME DATETIME NULL    COMMENT '操作时间',
  OP_USER VARCHAR(255) NULL    COMMENT '操作人姓名',
  SIGN_DATA LONGTEXT NULL    COMMENT '签名数据',
  CREATE_TIME DATETIME NULL    COMMENT '创建时间',
  CREATE_USER VARCHAR(20) NULL    COMMENT '创建用户',
  UPDATE_TIME DATETIME NULL    COMMENT '修改时间',
  UPDATE_USER VARCHAR(20) NULL    COMMENT '修改用户',
  constraint PK_DEV_LOG primary key (ID)
);

CREATE TABLE DEV_MESSAGE(
  ID VARCHAR(20) NOT NULL    COMMENT 'Id',
  CATEGORY VARCHAR(255) NULL    COMMENT '分类',
  SUBJECT TEXT NULL    COMMENT '主题',
  CONTENT LONGTEXT NULL    COMMENT '正文',
  EXT_JSON LONGTEXT NULL    COMMENT '扩展信息',
  DELETE_FLAG VARCHAR(255) NULL    COMMENT '删除标志',
  CREATE_TIME DATETIME NULL    COMMENT '创建时间',
  CREATE_USER VARCHAR(20) NULL    COMMENT '创建用户',
  UPDATE_TIME DATETIME NULL    COMMENT '修改时间',
  UPDATE_USER VARCHAR(20) NULL    COMMENT '修改用户',
  constraint PK_DEV_MESSAGE primary key (ID)
);

CREATE TABLE DEV_RELATION(
  ID VARCHAR(20) NOT NULL    COMMENT 'Id',
  OBJECT_ID VARCHAR(255) NULL    COMMENT '对象ID',
  TARGET_ID VARCHAR(255) NULL    COMMENT '目标ID',
  CATEGORY VARCHAR(255) NULL    COMMENT '分类',
  EXT_JSON LONGTEXT NULL    COMMENT '扩展信息',
  constraint PK_DEV_RELATION primary key (ID)
);

CREATE TABLE DEV_SLIDESHOW(
  ID VARCHAR(20) NOT NULL    COMMENT '主键',
  TITLE VARCHAR(200) NULL    COMMENT '标题',
  PLACE VARCHAR(500) NULL    COMMENT '展示位置',
  IMAGE VARCHAR(200) NULL    COMMENT '图片',
  PATH_DETAILS VARCHAR(500) NULL    COMMENT '路径详情',
  STATUS VARCHAR(10) NULL    COMMENT '状态',
  SORT_CODE INTEGER NULL    COMMENT '排序',
  EXT_JSON LONGTEXT NULL    COMMENT '扩展信息',
  DELETE_FLAG VARCHAR(255) NULL    COMMENT '删除标志',
  CREATE_TIME DATETIME NULL    COMMENT '创建时间',
  CREATE_USER VARCHAR(20) NULL    COMMENT '创建用户',
  UPDATE_TIME DATETIME NULL    COMMENT '更新时间',
  UPDATE_USER VARCHAR(20) NULL    COMMENT '更新用户',
  constraint PK_DEV_SLIDESHOW primary key (ID)
);

CREATE TABLE DEV_SMS(
  ID VARCHAR(20) NOT NULL    COMMENT 'Id',
  ENGINE VARCHAR(255) NULL    COMMENT '短信引擎',
  PHONE_NUMBERS TEXT NULL    COMMENT '手机号',
  SIGN_NAME TEXT NULL    COMMENT '短信签名',
  TEMPLATE_CODE TEXT NULL    COMMENT '模板编码',
  TEMPLATE_PARAM TEXT NULL    COMMENT '发送参数',
  RECEIPT_INFO LONGTEXT NULL    COMMENT '回执信息',
  EXT_JSON LONGTEXT NULL    COMMENT '扩展信息',
  DELETE_FLAG VARCHAR(255) NULL    COMMENT '删除标志',
  CREATE_TIME DATETIME NULL    COMMENT '创建时间',
  CREATE_USER VARCHAR(20) NULL    COMMENT '创建用户',
  UPDATE_TIME DATETIME NULL    COMMENT '修改时间',
  UPDATE_USER VARCHAR(20) NULL    COMMENT '修改用户',
  constraint PK_DEV_SMS primary key (ID)
);


   ALTER TABLE DEV_CONFIG COMMENT '配置';
                
   ALTER TABLE DEV_DICT COMMENT '字典';
                
   ALTER TABLE DEV_EMAIL COMMENT '邮件';
                
   ALTER TABLE DEV_FILE COMMENT '文件';
                
   ALTER TABLE DEV_JOB COMMENT '定时任务';
                
   ALTER TABLE DEV_LOG COMMENT '日志';
                
   ALTER TABLE DEV_MESSAGE COMMENT '站内信';
                
   ALTER TABLE DEV_RELATION COMMENT '关系';
                
   ALTER TABLE DEV_SLIDESHOW COMMENT '轮播图';
                
   ALTER TABLE DEV_SMS COMMENT '短信';
                
