
CREATE TABLE DAHUA_CAMERA(
  ID VARCHAR(20) NOT NULL    COMMENT '主键',
  DEVICE_ID VARCHAR(64) NULL    COMMENT '设备编号',
  NAME VARCHAR(128) NOT NULL    COMMENT '设备名称',
  IP_ADDR VARCHAR(64) NOT NULL    COMMENT '设备IP地址',
  PORT INTEGER NOT NULL    COMMENT '端口号',
  USERNAME VARCHAR(64) NOT NULL    COMMENT '用户名',
  PASSWORD VARCHAR(128) NOT NULL    COMMENT '密码',
  ENABLE_STATUS BOOLEAN default 1  NOT NULL    COMMENT '启用状态：1=启用，0=禁用',
  ONLINE_STATUS BOOLEAN default 0  NOT NULL    COMMENT '在线状态：1=在线，0=离线',
  CREATE_TIME DATETIME NOT NULL    COMMENT '创建时间',
  UPDATE_TIME DATETIME NOT NULL    COMMENT '更新时间',
  constraint IDX_DAHUA_CAMERA_NAME unique (NAME),
  constraint PK_DAHUA_CAMERA primary key (ID)
);


   ALTER TABLE DAHUA_CAMERA COMMENT '大华设备表';
                
