
CREATE TABLE DAHUA_CAMERA(
  ID INT8 NOT NULL ,
  DEVICE_ID VARCHAR(64)  ,
  NAME VARCHAR(128) NOT NULL ,
  IP_ADDR VARCHAR(64) NOT NULL ,
  PORT INT4 NOT NULL ,
  USERNAME VARCHAR(64) NOT NULL ,
  PASSWORD VARCHAR(128) NOT NULL ,
  ENABLE_STATUS INT4 default 1  NOT NULL ,
  ONLINE_STATUS INT4 default 0  NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint IDX_DAHUA_CAMERA_DEVICE_ID unique (DEVICE_ID),
  constraint IDX_DAHUA_CAMERA_NAME unique (NAME),
  constraint IDX_DAHUA_CAMERA_IP_ADDR unique (IP_ADDR),
  constraint PK_DAHUA_CAMERA primary key (ID)
);

CREATE TABLE DAHUA_NON_MOTOR_VEHICLE(
  ABSSCORE INT4  ,
  ACCOMPANYNUMBER INT4  ,
  ACCOMPANYNUMBERRELIABILITY INT4  ,
  AGE INT4  ,
  AGEGROUP INT4  ,
  AGEGROUPRELIABILITY INT4  ,
  AGELOWERLIMIT INT4  ,
  AGERELIABILITY INT4  ,
  AGEUPLIMIT INT4  ,
  ALGORITHMVERSION VARCHAR(50)  ,
  ALIAS VARCHAR(255)  ,
  APPENDANT VARCHAR(10)  ,
  APPENDANTDESCRIPTION TEXT  ,
  BABY VARCHAR(10)  ,
  BAG1RELIABILITY INT4  ,
  BAG1STYLE VARCHAR(10)  ,
  BAG2RELIABILITY INT4  ,
  BAG2STYLE VARCHAR(10)  ,
  BAG3RELIABILITY INT4  ,
  BAG3STYLE VARCHAR(10)  ,
  BAGCOLOR VARCHAR(10)  ,
  BAGSTYLE VARCHAR(10)  ,
  BAGSTYLERELIABILITY INT4  ,
  BEHAVIOR TEXT  ,
  BEHAVIORDESCRIPTION TEXT  ,
  BODYFEATURE TEXT  ,
  BODYSPECIALLMARK TEXT  ,
  BODYTYPE VARCHAR(255)  ,
  CACHEIMGURL TEXT  ,
  CACHEPLATEIMGURL TEXT  ,
  CACHETARGETIMGURL TEXT  ,
  CAPCOLOR VARCHAR(10)  ,
  CAPCOLORRELIABILITY INT4  ,
  CAPSTYLE VARCHAR(10)  ,
  CAPSTYLERELIABILITY INT4  ,
  CAPTIME INT8  ,
  CHANNELCODE VARCHAR(100)  ,
  CHANNELID VARCHAR(100)  ,
  CHINESEACCENTCODE VARCHAR(255)  ,
  COATCOLOR VARCHAR(10)  ,
  COATCOLORRELIABILITY INT4  ,
  COATLENGTH VARCHAR(10)  ,
  COATLENGTHRELIABILITY INT4  ,
  COATSTYLE VARCHAR(10)  ,
  COATSTYLERELIABILITY INT4  ,
  COATTEXTURE VARCHAR(10)  ,
  COATTEXTURERELIABILITY INT4  ,
  COMPLETESCORE INT4  ,
  CORPSECONDITIONCODE VARCHAR(255)  ,
  CRIMECHARACTERCODE VARCHAR(255)  ,
  CRIMEMETHOD TEXT  ,
  CRIMINALINVOLVEDCODE VARCHAR(255)  ,
  DATASOURCE INT4  ,
  DATATRACETAG TEXT  ,
  DETAINEESIDENTITY VARCHAR(255)  ,
  DETAINEESSPECIALIDENTITY VARCHAR(255)  ,
  DETECTOBJECT INT4  ,
  DETECTIONSCORE INT4  ,
  DETENTIONHOUSECODE VARCHAR(255)  ,
  DEVICECODE VARCHAR(255)  ,
  DEVICEID VARCHAR(100)  ,
  EMCLASSTYPE INT4  ,
  ESCAPEDCRIMINALNUMBER VARCHAR(255)  ,
  EVENT VARCHAR(50)  ,
  EXTRECORDID VARCHAR(255)  ,
  EXTRECORDSOURCE INT4  ,
  EXTRACTEDFLAG INT4  ,
  FACEDIRECT INT4  ,
  FACEDIRECTRELIABILITY INT4  ,
  FACESTYLE VARCHAR(255)  ,
  FACIALFEATURE TEXT  ,
  FEATUREDATA TEXT  ,
  FEATUREID VARCHAR(100)  ,
  GENDER INT4  ,
  GENDERRELIABILITY INT4  ,
  GESTURE VARCHAR(10)  ,
  GLASSCOLOR VARCHAR(10)  ,
  GLASSSTYLE VARCHAR(255)  ,
  HABITUALMOVEMEN VARCHAR(10)  ,
  HAIRCOLOR VARCHAR(255)  ,
  HAIRSTYLE VARCHAR(10)  ,
  HAIRSTYLERELIABILITY INT4  ,
  HAIRTYPE INT4  ,
  HASBAG INT4  ,
  HASBAGRELIABILITY INT4  ,
  HASBASKET INT4  ,
  HASCARRIERBAG INT4  ,
  HASCARRYSTUFF INT4  ,
  HASCART INT4  ,
  HASDOWNBODY INT4  ,
  HASDOWNBODYRELIABILITY INT4  ,
  HASERRORDETECT INT4  ,
  HASHEAD INT4  ,
  HASHEADRELIABILITY INT4  ,
  HASMIRROR INT4  ,
  HASRAINCOAT INT4  ,
  HASRESPIRATOR INT4  ,
  HASTRUNK INT4  ,
  HASVEHICLE INT4  ,
  HASVEST INT4  ,
  HASVESTRELIABILITY INT4  ,
  HAT INT4  ,
  HATRELIABILITY INT4  ,
  HEIGHTLOWERLIMIT INT4  ,
  HEIGHTUPLIMIT INT4  ,
  HUMANLIST TEXT  ,
  IDNUMBER VARCHAR(255)  ,
  IDTYPE VARCHAR(255)  ,
  IMGHEIGHT INT4  ,
  IMGURL TEXT  ,
  IMGWIDTH INT4  ,
  IMMIGRANTTYPECODE VARCHAR(255)  ,
  INFOKIND INT4  ,
  INJUREDDEGREE VARCHAR(10)  ,
  IQASCORE INT4  ,
  ISCRIMINALINVOLVED INT4  ,
  ISDETAINEES INT4  ,
  ISDRIVER INT4  ,
  ISFOREIGNER INT4  ,
  ISNONCOMPLETE INT4  ,
  ISSUSPECTEDTERRORIST INT4  ,
  ISSUSPICIOUSPERSON INT4  ,
  ISVICTIM INT4  ,
  JOBCATEGORY VARCHAR(255)  ,
  LOCATIONMARKTIME INT8  ,
  MASK INT4  ,
  MASKCOLOR INT4  ,
  MEMBERTYPECODE VARCHAR(255)  ,
  NAME VARCHAR(255)  ,
  NATIONALITYCODE VARCHAR(255)  ,
  NATIVECITYCODE VARCHAR(255)  ,
  NONVEHICLEUMBRELLACOLOR VARCHAR(10)  ,
  NONVEHICLEUMBRELLATYPE INT4  ,
  NONVEHICLEUMBRELLATYPERELIABILITY INT4  ,
  OBJSIZE INT4  ,
  OBJECTSUBTYPE INT4  ,
  PASSENGER INT4  ,
  PASSPORTTYPE VARCHAR(255)  ,
  PERSONAPPEARTIME INT8  ,
  PERSONBOTTOM INT4  ,
  PERSONDISAPPEARTIME INT8  ,
  PERSONIMGID VARCHAR(100)  ,
  PERSONLEFT INT4  ,
  PERSONORG VARCHAR(255)  ,
  PERSONRIGHT INT4  ,
  PERSONTOP INT4  ,
  PHYSICALFEATURE TEXT  ,
  PICRECORDID VARCHAR(100)  ,
  PLATEBOTTOM INT4  ,
  PLATECOLOR VARCHAR(255)  ,
  PLATEIMGURL TEXT  ,
  PLATELEFT INT4  ,
  PLATENUM VARCHAR(255)  ,
  PLATERIGHT INT4  ,
  PLATETOP INT4  ,
  POSTURE INT4  ,
  POSTURERELIABILITY INT4  ,
  PREVMSGRECORDID VARCHAR(100)  ,
  QESCORE INT4  ,
  RAINCOATRELIABILITY INT4  ,
  RECORDID VARCHAR(100)  ,
  RELATEDFACE INT4  ,
  RELATEDGAIT INT4  ,
  RELATEDNONVEHICLE INT4  ,
  RELATEDNONVEHICLELIST TEXT  ,
  RELATEDPERSON INT4  ,
  RELIABLITY INT4  ,
  RESIDENCEADMINDIVISION VARCHAR(255)  ,
  RESPIRATORCOLOR VARCHAR(10)  ,
  RFIDINFO TEXT  ,
  RIDERVEHICLE INT4  ,
  SNUMBER VARCHAR(10)  ,
  SCARFCOLOR VARCHAR(10)  ,
  SHOESCOLOR VARCHAR(10)  ,
  SHOESSTYLE VARCHAR(10)  ,
  SKINCOLOR VARCHAR(255)  ,
  SOURCEID VARCHAR(100)  ,
  STATUS VARCHAR(10)  ,
  SUSPECTEDTERRORISTNUMBER VARCHAR(255)  ,
  TARGETIMGURL TEXT  ,
  TRACESERVICEINPUTTIME INT8  ,
  TRACETHINGSINPUTTIME INT8  ,
  TROUSERSCOLOR VARCHAR(10)  ,
  TROUSERSCOLORRELIABILITY INT4  ,
  TROUSERSLEN VARCHAR(10)  ,
  TROUSERSLENRELIABILITY INT4  ,
  TROUSERSSTYLE VARCHAR(10)  ,
  UID VARCHAR(10)  ,
  UMBRELLA INT4  ,
  UMBRELLACOLOR VARCHAR(10)  ,
  UMBRELLARELIABILITY INT4  ,
  UNIFORMSTYLE INT4  ,
  UNIFORMSTYLERELIABILITY INT4  ,
  USEDNAME VARCHAR(255)  ,
  USERCHANNELCODE VARCHAR(100)  ,
  VEHICLECOLOR VARCHAR(10)  ,
  VEHICLETYPE INT4  ,
  VEHICLETYPERELIABILITY INT4  ,
  VENDOR VARCHAR(10)  ,
  VICTIMTYPE VARCHAR(255)  ,
  constraint PK_DAHUA_NON_MOTOR_VEHICLE primary key (ABSSCORE)
);


      COMMENT ON TABLE DAHUA_CAMERA IS '大华设备表';
                
      COMMENT ON COLUMN DAHUA_CAMERA.ID IS '主键';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.DEVICE_ID IS '设备编号';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.NAME IS '设备名称';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.IP_ADDR IS '设备IP地址';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.PORT IS '端口号';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.USERNAME IS '用户名';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.PASSWORD IS '密码';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.ENABLE_STATUS IS '启用状态：1=启用，0=禁用';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.ONLINE_STATUS IS '在线状态：1=在线，0=离线';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.UPDATE_TIME IS '更新时间';
                    
      COMMENT ON TABLE DAHUA_NON_MOTOR_VEHICLE IS 'Dahuanonmotorvehicle';
                
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ABSSCORE IS 'Absscore';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ACCOMPANYNUMBER IS 'Accompanynumber';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ACCOMPANYNUMBERRELIABILITY IS 'Accompanynumberreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.AGE IS 'Age';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.AGEGROUP IS 'Agegroup';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.AGEGROUPRELIABILITY IS 'Agegroupreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.AGELOWERLIMIT IS 'Agelowerlimit';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.AGERELIABILITY IS 'Agereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.AGEUPLIMIT IS 'Ageuplimit';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ALGORITHMVERSION IS 'Algorithmversion';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ALIAS IS 'Alias';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.APPENDANT IS 'Appendant';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.APPENDANTDESCRIPTION IS 'Appendantdescription';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BABY IS 'Baby';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAG1RELIABILITY IS 'Bag1reliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAG1STYLE IS 'Bag1style';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAG2RELIABILITY IS 'Bag2reliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAG2STYLE IS 'Bag2style';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAG3RELIABILITY IS 'Bag3reliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAG3STYLE IS 'Bag3style';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAGCOLOR IS 'Bagcolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAGSTYLE IS 'Bagstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAGSTYLERELIABILITY IS 'Bagstylereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BEHAVIOR IS 'Behavior';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BEHAVIORDESCRIPTION IS 'Behaviordescription';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BODYFEATURE IS 'Bodyfeature';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BODYSPECIALLMARK IS 'Bodyspeciallmark';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BODYTYPE IS 'Bodytype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CACHEIMGURL IS 'Cacheimgurl';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CACHEPLATEIMGURL IS 'Cacheplateimgurl';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CACHETARGETIMGURL IS 'Cachetargetimgurl';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CAPCOLOR IS 'Capcolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CAPCOLORRELIABILITY IS 'Capcolorreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CAPSTYLE IS 'Capstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CAPSTYLERELIABILITY IS 'Capstylereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CAPTIME IS 'Captime';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CHANNELCODE IS 'Channelcode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CHANNELID IS 'Channelid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CHINESEACCENTCODE IS 'Chineseaccentcode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATCOLOR IS 'Coatcolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATCOLORRELIABILITY IS 'Coatcolorreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATLENGTH IS 'Coatlength';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATLENGTHRELIABILITY IS 'Coatlengthreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATSTYLE IS 'Coatstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATSTYLERELIABILITY IS 'Coatstylereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATTEXTURE IS 'Coattexture';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATTEXTURERELIABILITY IS 'Coattexturereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COMPLETESCORE IS 'Completescore';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CORPSECONDITIONCODE IS 'Corpseconditioncode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CRIMECHARACTERCODE IS 'Crimecharactercode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CRIMEMETHOD IS 'Crimemethod';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CRIMINALINVOLVEDCODE IS 'Criminalinvolvedcode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DATASOURCE IS 'Datasource';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DATATRACETAG IS 'Datatracetag';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DETAINEESIDENTITY IS 'Detaineesidentity';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DETAINEESSPECIALIDENTITY IS 'Detaineesspecialidentity';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DETECTOBJECT IS 'Detectobject';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DETECTIONSCORE IS 'Detectionscore';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DETENTIONHOUSECODE IS 'Detentionhousecode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DEVICECODE IS 'Devicecode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DEVICEID IS 'Deviceid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.EMCLASSTYPE IS 'Emclasstype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ESCAPEDCRIMINALNUMBER IS 'Escapedcriminalnumber';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.EVENT IS 'Event';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.EXTRECORDID IS 'Extrecordid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.EXTRECORDSOURCE IS 'Extrecordsource';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.EXTRACTEDFLAG IS 'Extractedflag';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.FACEDIRECT IS 'Facedirect';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.FACEDIRECTRELIABILITY IS 'Facedirectreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.FACESTYLE IS 'Facestyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.FACIALFEATURE IS 'Facialfeature';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.FEATUREDATA IS 'Featuredata';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.FEATUREID IS 'Featureid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.GENDER IS 'Gender';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.GENDERRELIABILITY IS 'Genderreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.GESTURE IS 'Gesture';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.GLASSCOLOR IS 'Glasscolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.GLASSSTYLE IS 'Glassstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HABITUALMOVEMEN IS 'Habitualmovemen';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HAIRCOLOR IS 'Haircolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HAIRSTYLE IS 'Hairstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HAIRSTYLERELIABILITY IS 'Hairstylereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HAIRTYPE IS 'Hairtype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASBAG IS 'Hasbag';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASBAGRELIABILITY IS 'Hasbagreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASBASKET IS 'Hasbasket';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASCARRIERBAG IS 'Hascarrierbag';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASCARRYSTUFF IS 'Hascarrystuff';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASCART IS 'Hascart';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASDOWNBODY IS 'Hasdownbody';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASDOWNBODYRELIABILITY IS 'Hasdownbodyreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASERRORDETECT IS 'Haserrordetect';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASHEAD IS 'Hashead';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASHEADRELIABILITY IS 'Hasheadreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASMIRROR IS 'Hasmirror';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASRAINCOAT IS 'Hasraincoat';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASRESPIRATOR IS 'Hasrespirator';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASTRUNK IS 'Hastrunk';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASVEHICLE IS 'Hasvehicle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASVEST IS 'Hasvest';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASVESTRELIABILITY IS 'Hasvestreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HAT IS 'Hat';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HATRELIABILITY IS 'Hatreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HEIGHTLOWERLIMIT IS 'Heightlowerlimit';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HEIGHTUPLIMIT IS 'Heightuplimit';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HUMANLIST IS 'Humanlist';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.IDNUMBER IS 'Idnumber';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.IDTYPE IS 'Idtype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.IMGHEIGHT IS 'Imgheight';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.IMGURL IS 'Imgurl';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.IMGWIDTH IS 'Imgwidth';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.IMMIGRANTTYPECODE IS 'Immigranttypecode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.INFOKIND IS 'Infokind';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.INJUREDDEGREE IS 'Injureddegree';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.IQASCORE IS 'Iqascore';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISCRIMINALINVOLVED IS 'Iscriminalinvolved';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISDETAINEES IS 'Isdetainees';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISDRIVER IS 'Isdriver';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISFOREIGNER IS 'Isforeigner';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISNONCOMPLETE IS 'Isnoncomplete';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISSUSPECTEDTERRORIST IS 'Issuspectedterrorist';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISSUSPICIOUSPERSON IS 'Issuspiciousperson';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISVICTIM IS 'Isvictim';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.JOBCATEGORY IS 'Jobcategory';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.LOCATIONMARKTIME IS 'Locationmarktime';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.MASK IS 'Mask';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.MASKCOLOR IS 'Maskcolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.MEMBERTYPECODE IS 'Membertypecode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.NAME IS 'Name';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.NATIONALITYCODE IS 'Nationalitycode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.NATIVECITYCODE IS 'Nativecitycode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.NONVEHICLEUMBRELLACOLOR IS 'Nonvehicleumbrellacolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.NONVEHICLEUMBRELLATYPE IS 'Nonvehicleumbrellatype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.NONVEHICLEUMBRELLATYPERELIABILITY IS 'Nonvehicleumbrellatypereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.OBJSIZE IS 'Objsize';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.OBJECTSUBTYPE IS 'Objectsubtype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PASSENGER IS 'Passenger';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PASSPORTTYPE IS 'Passporttype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONAPPEARTIME IS 'Personappeartime';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONBOTTOM IS 'Personbottom';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONDISAPPEARTIME IS 'Persondisappeartime';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONIMGID IS 'Personimgid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONLEFT IS 'Personleft';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONORG IS 'Personorg';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONRIGHT IS 'Personright';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONTOP IS 'Persontop';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PHYSICALFEATURE IS 'Physicalfeature';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PICRECORDID IS 'Picrecordid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PLATEBOTTOM IS 'Platebottom';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PLATECOLOR IS 'Platecolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PLATEIMGURL IS 'Plateimgurl';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PLATELEFT IS 'Plateleft';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PLATENUM IS 'Platenum';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PLATERIGHT IS 'Plateright';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PLATETOP IS 'Platetop';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.POSTURE IS 'Posture';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.POSTURERELIABILITY IS 'Posturereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PREVMSGRECORDID IS 'Prevmsgrecordid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.QESCORE IS 'Qescore';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RAINCOATRELIABILITY IS 'Raincoatreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RECORDID IS 'Recordid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RELATEDFACE IS 'Relatedface';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RELATEDGAIT IS 'Relatedgait';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RELATEDNONVEHICLE IS 'Relatednonvehicle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RELATEDNONVEHICLELIST IS 'Relatednonvehiclelist';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RELATEDPERSON IS 'Relatedperson';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RELIABLITY IS 'Reliablity';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RESIDENCEADMINDIVISION IS 'Residenceadmindivision';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RESPIRATORCOLOR IS 'Respiratorcolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RFIDINFO IS 'Rfidinfo';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RIDERVEHICLE IS 'Ridervehicle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.SNUMBER IS 'Snumber';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.SCARFCOLOR IS 'Scarfcolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.SHOESCOLOR IS 'Shoescolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.SHOESSTYLE IS 'Shoesstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.SKINCOLOR IS 'Skincolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.SOURCEID IS 'Sourceid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.STATUS IS 'Status';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.SUSPECTEDTERRORISTNUMBER IS 'Suspectedterroristnumber';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TARGETIMGURL IS 'Targetimgurl';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TRACESERVICEINPUTTIME IS 'Traceserviceinputtime';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TRACETHINGSINPUTTIME IS 'Tracethingsinputtime';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TROUSERSCOLOR IS 'Trouserscolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TROUSERSCOLORRELIABILITY IS 'Trouserscolorreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TROUSERSLEN IS 'Trouserslen';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TROUSERSLENRELIABILITY IS 'Trouserslenreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TROUSERSSTYLE IS 'Trousersstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.UID IS 'Uid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.UMBRELLA IS 'Umbrella';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.UMBRELLACOLOR IS 'Umbrellacolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.UMBRELLARELIABILITY IS 'Umbrellareliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.UNIFORMSTYLE IS 'Uniformstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.UNIFORMSTYLERELIABILITY IS 'Uniformstylereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.USEDNAME IS 'Usedname';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.USERCHANNELCODE IS 'Userchannelcode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.VEHICLECOLOR IS 'Vehiclecolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.VEHICLETYPE IS 'Vehicletype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.VEHICLETYPERELIABILITY IS 'Vehicletypereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.VENDOR IS 'Vendor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.VICTIMTYPE IS 'Victimtype';
                    
