
CREATE TABLE DAHUA_CAMERA(
  ID VARCHAR(32) NOT NULL ,
  DEVICE_ID VARCHAR(64)  ,
  NAME VARCHAR(128) NOT NULL ,
  IP_ADDR VARCHAR(64) NOT NULL ,
  PORT INT4 NOT NULL ,
  USERNAME VARCHAR(64) NOT NULL ,
  PASSWORD VARCHAR(128) NOT NULL ,
  ENABLE_STATUS INT4 default 1  NOT NULL ,
  ONLINE_STATUS INT4 default 0  NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint IDX_DAHUA_CAMERA_NAME unique (NAME),
  constraint PK_DAHUA_CAMERA primary key (ID)
);


      COMMENT ON TABLE DAHUA_CAMERA IS '大华设备表';
                
      COMMENT ON COLUMN DAHUA_CAMERA.ID IS '主键';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.DEVICE_ID IS '设备编号';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.NAME IS '设备名称';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.IP_ADDR IS '设备IP地址';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.PORT IS '端口号';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.USERNAME IS '用户名';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.PASSWORD IS '密码';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.ENABLE_STATUS IS '启用状态：1=启用，0=禁用';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.ONLINE_STATUS IS '在线状态：1=在线，0=离线';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.UPDATE_TIME IS '更新时间';
                    
