
CREATE TABLE DAHUA_CAMERA(
  ID BIGINT NOT NULL  COMMENT '主键' ,
  DEVICE_ID VARCHAR(64)   COMMENT '设备编号' ,
  NAME VARCHAR(128) NOT NULL  COMMENT '设备名称' ,
  IP_ADDR VARCHAR(64) NOT NULL  COMMENT '设备IP地址' ,
  PORT INTEGER NOT NULL  COMMENT '端口号' ,
  USERNAME VARCHAR(64) NOT NULL  COMMENT '用户名' ,
  PASSWORD VARCHAR(128) NOT NULL  COMMENT '密码' ,
  ENABLE_STATUS INTEGER default 1  NOT NULL  COMMENT '启用状态：1=启用，0=禁用' ,
  ONLINE_STATUS INTEGER default 0  NOT NULL  COMMENT '在线状态：1=在线，0=离线' ,
  CREATE_TIME TIMESTAMP NOT NULL  COMMENT '创建时间' ,
  UPDATE_TIME TIMESTAMP NOT NULL  COMMENT '更新时间' ,
  constraint IDX_DAHUA_CAMERA_DEVICE_ID unique (DEVICE_ID),
  constraint IDX_DAHUA_CAMERA_NAME unique (NAME),
  constraint IDX_DAHUA_CAMERA_IP_ADDR unique (IP_ADDR),
  constraint PK_DAHUA_CAMERA primary key (ID)
);

CREATE TABLE DAHUA_NON_MOTOR_VEHICLE(
  ABSSCORE INTEGER   COMMENT 'Absscore' ,
  ACCOMPANYNUMBER INTEGER   COMMENT 'Accompanynumber' ,
  ACCOMPANYNUMBERRELIABILITY INTEGER   COMMENT 'Accompanynumberreliability' ,
  AGE INTEGER   COMMENT 'Age' ,
  AGEGROUP INTEGER   COMMENT 'Agegroup' ,
  AGEGROUPRELIABILITY INTEGER   COMMENT 'Agegroupreliability' ,
  AGELOWERLIMIT INTEGER   COMMENT 'Agelowerlimit' ,
  AGERELIABILITY INTEGER   COMMENT 'Agereliability' ,
  AGEUPLIMIT INTEGER   COMMENT 'Ageuplimit' ,
  ALGORITHMVERSION VARCHAR(50)   COMMENT 'Algorithmversion' ,
  ALIAS VARCHAR(255)   COMMENT 'Alias' ,
  APPENDANT VARCHAR(10)   COMMENT 'Appendant' ,
  APPENDANTDESCRIPTION VARCHAR(65535)   COMMENT 'Appendantdescription' ,
  BABY VARCHAR(10)   COMMENT 'Baby' ,
  BAG1RELIABILITY INTEGER   COMMENT 'Bag1reliability' ,
  BAG1STYLE VARCHAR(10)   COMMENT 'Bag1style' ,
  BAG2RELIABILITY INTEGER   COMMENT 'Bag2reliability' ,
  BAG2STYLE VARCHAR(10)   COMMENT 'Bag2style' ,
  BAG3RELIABILITY INTEGER   COMMENT 'Bag3reliability' ,
  BAG3STYLE VARCHAR(10)   COMMENT 'Bag3style' ,
  BAGCOLOR VARCHAR(10)   COMMENT 'Bagcolor' ,
  BAGSTYLE VARCHAR(10)   COMMENT 'Bagstyle' ,
  BAGSTYLERELIABILITY INTEGER   COMMENT 'Bagstylereliability' ,
  BEHAVIOR VARCHAR(65535)   COMMENT 'Behavior' ,
  BEHAVIORDESCRIPTION VARCHAR(65535)   COMMENT 'Behaviordescription' ,
  BODYFEATURE VARCHAR(65535)   COMMENT 'Bodyfeature' ,
  BODYSPECIALLMARK VARCHAR(65535)   COMMENT 'Bodyspeciallmark' ,
  BODYTYPE VARCHAR(255)   COMMENT 'Bodytype' ,
  CACHEIMGURL VARCHAR(65535)   COMMENT 'Cacheimgurl' ,
  CACHEPLATEIMGURL VARCHAR(65535)   COMMENT 'Cacheplateimgurl' ,
  CACHETARGETIMGURL VARCHAR(65535)   COMMENT 'Cachetargetimgurl' ,
  CAPCOLOR VARCHAR(10)   COMMENT 'Capcolor' ,
  CAPCOLORRELIABILITY INTEGER   COMMENT 'Capcolorreliability' ,
  CAPSTYLE VARCHAR(10)   COMMENT 'Capstyle' ,
  CAPSTYLERELIABILITY INTEGER   COMMENT 'Capstylereliability' ,
  CAPTIME BIGINT   COMMENT 'Captime' ,
  CHANNELCODE VARCHAR(100)   COMMENT 'Channelcode' ,
  CHANNELID VARCHAR(100)   COMMENT 'Channelid' ,
  CHINESEACCENTCODE VARCHAR(255)   COMMENT 'Chineseaccentcode' ,
  COATCOLOR VARCHAR(10)   COMMENT 'Coatcolor' ,
  COATCOLORRELIABILITY INTEGER   COMMENT 'Coatcolorreliability' ,
  COATLENGTH VARCHAR(10)   COMMENT 'Coatlength' ,
  COATLENGTHRELIABILITY INTEGER   COMMENT 'Coatlengthreliability' ,
  COATSTYLE VARCHAR(10)   COMMENT 'Coatstyle' ,
  COATSTYLERELIABILITY INTEGER   COMMENT 'Coatstylereliability' ,
  COATTEXTURE VARCHAR(10)   COMMENT 'Coattexture' ,
  COATTEXTURERELIABILITY INTEGER   COMMENT 'Coattexturereliability' ,
  COMPLETESCORE INTEGER   COMMENT 'Completescore' ,
  CORPSECONDITIONCODE VARCHAR(255)   COMMENT 'Corpseconditioncode' ,
  CRIMECHARACTERCODE VARCHAR(255)   COMMENT 'Crimecharactercode' ,
  CRIMEMETHOD VARCHAR(65535)   COMMENT 'Crimemethod' ,
  CRIMINALINVOLVEDCODE VARCHAR(255)   COMMENT 'Criminalinvolvedcode' ,
  DATASOURCE INTEGER   COMMENT 'Datasource' ,
  DATATRACETAG VARCHAR(65535)   COMMENT 'Datatracetag' ,
  DETAINEESIDENTITY VARCHAR(255)   COMMENT 'Detaineesidentity' ,
  DETAINEESSPECIALIDENTITY VARCHAR(255)   COMMENT 'Detaineesspecialidentity' ,
  DETECTOBJECT INTEGER   COMMENT 'Detectobject' ,
  DETECTIONSCORE INTEGER   COMMENT 'Detectionscore' ,
  DETENTIONHOUSECODE VARCHAR(255)   COMMENT 'Detentionhousecode' ,
  DEVICECODE VARCHAR(255)   COMMENT 'Devicecode' ,
  DEVICEID VARCHAR(100)   COMMENT 'Deviceid' ,
  EMCLASSTYPE INTEGER   COMMENT 'Emclasstype' ,
  ESCAPEDCRIMINALNUMBER VARCHAR(255)   COMMENT 'Escapedcriminalnumber' ,
  EVENT VARCHAR(50)   COMMENT 'Event' ,
  EXTRECORDID VARCHAR(255)   COMMENT 'Extrecordid' ,
  EXTRECORDSOURCE INTEGER   COMMENT 'Extrecordsource' ,
  EXTRACTEDFLAG INTEGER   COMMENT 'Extractedflag' ,
  FACEDIRECT INTEGER   COMMENT 'Facedirect' ,
  FACEDIRECTRELIABILITY INTEGER   COMMENT 'Facedirectreliability' ,
  FACESTYLE VARCHAR(255)   COMMENT 'Facestyle' ,
  FACIALFEATURE VARCHAR(65535)   COMMENT 'Facialfeature' ,
  FEATUREDATA VARCHAR(65535)   COMMENT 'Featuredata' ,
  FEATUREID VARCHAR(100)   COMMENT 'Featureid' ,
  GENDER INTEGER   COMMENT 'Gender' ,
  GENDERRELIABILITY INTEGER   COMMENT 'Genderreliability' ,
  GESTURE VARCHAR(10)   COMMENT 'Gesture' ,
  GLASSCOLOR VARCHAR(10)   COMMENT 'Glasscolor' ,
  GLASSSTYLE VARCHAR(255)   COMMENT 'Glassstyle' ,
  HABITUALMOVEMEN VARCHAR(10)   COMMENT 'Habitualmovemen' ,
  HAIRCOLOR VARCHAR(255)   COMMENT 'Haircolor' ,
  HAIRSTYLE VARCHAR(10)   COMMENT 'Hairstyle' ,
  HAIRSTYLERELIABILITY INTEGER   COMMENT 'Hairstylereliability' ,
  HAIRTYPE INTEGER   COMMENT 'Hairtype' ,
  HASBAG INTEGER   COMMENT 'Hasbag' ,
  HASBAGRELIABILITY INTEGER   COMMENT 'Hasbagreliability' ,
  HASBASKET INTEGER   COMMENT 'Hasbasket' ,
  HASCARRIERBAG INTEGER   COMMENT 'Hascarrierbag' ,
  HASCARRYSTUFF INTEGER   COMMENT 'Hascarrystuff' ,
  HASCART INTEGER   COMMENT 'Hascart' ,
  HASDOWNBODY INTEGER   COMMENT 'Hasdownbody' ,
  HASDOWNBODYRELIABILITY INTEGER   COMMENT 'Hasdownbodyreliability' ,
  HASERRORDETECT INTEGER   COMMENT 'Haserrordetect' ,
  HASHEAD INTEGER   COMMENT 'Hashead' ,
  HASHEADRELIABILITY INTEGER   COMMENT 'Hasheadreliability' ,
  HASMIRROR INTEGER   COMMENT 'Hasmirror' ,
  HASRAINCOAT INTEGER   COMMENT 'Hasraincoat' ,
  HASRESPIRATOR INTEGER   COMMENT 'Hasrespirator' ,
  HASTRUNK INTEGER   COMMENT 'Hastrunk' ,
  HASVEHICLE INTEGER   COMMENT 'Hasvehicle' ,
  HASVEST INTEGER   COMMENT 'Hasvest' ,
  HASVESTRELIABILITY INTEGER   COMMENT 'Hasvestreliability' ,
  HAT INTEGER   COMMENT 'Hat' ,
  HATRELIABILITY INTEGER   COMMENT 'Hatreliability' ,
  HEIGHTLOWERLIMIT INTEGER   COMMENT 'Heightlowerlimit' ,
  HEIGHTUPLIMIT INTEGER   COMMENT 'Heightuplimit' ,
  HUMANLIST VARCHAR(65535)   COMMENT 'Humanlist' ,
  IDNUMBER VARCHAR(255)   COMMENT 'Idnumber' ,
  IDTYPE VARCHAR(255)   COMMENT 'Idtype' ,
  IMGHEIGHT INTEGER   COMMENT 'Imgheight' ,
  IMGURL VARCHAR(65535)   COMMENT 'Imgurl' ,
  IMGWIDTH INTEGER   COMMENT 'Imgwidth' ,
  IMMIGRANTTYPECODE VARCHAR(255)   COMMENT 'Immigranttypecode' ,
  INFOKIND INTEGER   COMMENT 'Infokind' ,
  INJUREDDEGREE VARCHAR(10)   COMMENT 'Injureddegree' ,
  IQASCORE INTEGER   COMMENT 'Iqascore' ,
  ISCRIMINALINVOLVED INTEGER   COMMENT 'Iscriminalinvolved' ,
  ISDETAINEES INTEGER   COMMENT 'Isdetainees' ,
  ISDRIVER INTEGER   COMMENT 'Isdriver' ,
  ISFOREIGNER INTEGER   COMMENT 'Isforeigner' ,
  ISNONCOMPLETE INTEGER   COMMENT 'Isnoncomplete' ,
  ISSUSPECTEDTERRORIST INTEGER   COMMENT 'Issuspectedterrorist' ,
  ISSUSPICIOUSPERSON INTEGER   COMMENT 'Issuspiciousperson' ,
  ISVICTIM INTEGER   COMMENT 'Isvictim' ,
  JOBCATEGORY VARCHAR(255)   COMMENT 'Jobcategory' ,
  LOCATIONMARKTIME BIGINT   COMMENT 'Locationmarktime' ,
  MASK INTEGER   COMMENT 'Mask' ,
  MASKCOLOR INTEGER   COMMENT 'Maskcolor' ,
  MEMBERTYPECODE VARCHAR(255)   COMMENT 'Membertypecode' ,
  NAME VARCHAR(255)   COMMENT 'Name' ,
  NATIONALITYCODE VARCHAR(255)   COMMENT 'Nationalitycode' ,
  NATIVECITYCODE VARCHAR(255)   COMMENT 'Nativecitycode' ,
  NONVEHICLEUMBRELLACOLOR VARCHAR(10)   COMMENT 'Nonvehicleumbrellacolor' ,
  NONVEHICLEUMBRELLATYPE INTEGER   COMMENT 'Nonvehicleumbrellatype' ,
  NONVEHICLEUMBRELLATYPERELIABILITY INTEGER   COMMENT 'Nonvehicleumbrellatypereliability' ,
  OBJSIZE INTEGER   COMMENT 'Objsize' ,
  OBJECTSUBTYPE INTEGER   COMMENT 'Objectsubtype' ,
  PASSENGER INTEGER   COMMENT 'Passenger' ,
  PASSPORTTYPE VARCHAR(255)   COMMENT 'Passporttype' ,
  PERSONAPPEARTIME BIGINT   COMMENT 'Personappeartime' ,
  PERSONBOTTOM INTEGER   COMMENT 'Personbottom' ,
  PERSONDISAPPEARTIME BIGINT   COMMENT 'Persondisappeartime' ,
  PERSONIMGID VARCHAR(100)   COMMENT 'Personimgid' ,
  PERSONLEFT INTEGER   COMMENT 'Personleft' ,
  PERSONORG VARCHAR(255)   COMMENT 'Personorg' ,
  PERSONRIGHT INTEGER   COMMENT 'Personright' ,
  PERSONTOP INTEGER   COMMENT 'Persontop' ,
  PHYSICALFEATURE VARCHAR(65535)   COMMENT 'Physicalfeature' ,
  PICRECORDID VARCHAR(100)   COMMENT 'Picrecordid' ,
  PLATEBOTTOM INTEGER   COMMENT 'Platebottom' ,
  PLATECOLOR VARCHAR(255)   COMMENT 'Platecolor' ,
  PLATEIMGURL VARCHAR(65535)   COMMENT 'Plateimgurl' ,
  PLATELEFT INTEGER   COMMENT 'Plateleft' ,
  PLATENUM VARCHAR(255)   COMMENT 'Platenum' ,
  PLATERIGHT INTEGER   COMMENT 'Plateright' ,
  PLATETOP INTEGER   COMMENT 'Platetop' ,
  POSTURE INTEGER   COMMENT 'Posture' ,
  POSTURERELIABILITY INTEGER   COMMENT 'Posturereliability' ,
  PREVMSGRECORDID VARCHAR(100)   COMMENT 'Prevmsgrecordid' ,
  QESCORE INTEGER   COMMENT 'Qescore' ,
  RAINCOATRELIABILITY INTEGER   COMMENT 'Raincoatreliability' ,
  RECORDID VARCHAR(100)   COMMENT 'Recordid' ,
  RELATEDFACE INTEGER   COMMENT 'Relatedface' ,
  RELATEDGAIT INTEGER   COMMENT 'Relatedgait' ,
  RELATEDNONVEHICLE INTEGER   COMMENT 'Relatednonvehicle' ,
  RELATEDNONVEHICLELIST VARCHAR(65535)   COMMENT 'Relatednonvehiclelist' ,
  RELATEDPERSON INTEGER   COMMENT 'Relatedperson' ,
  RELIABLITY INTEGER   COMMENT 'Reliablity' ,
  RESIDENCEADMINDIVISION VARCHAR(255)   COMMENT 'Residenceadmindivision' ,
  RESPIRATORCOLOR VARCHAR(10)   COMMENT 'Respiratorcolor' ,
  RFIDINFO VARCHAR(65535)   COMMENT 'Rfidinfo' ,
  RIDERVEHICLE INTEGER   COMMENT 'Ridervehicle' ,
  SNUMBER VARCHAR(10)   COMMENT 'Snumber' ,
  SCARFCOLOR VARCHAR(10)   COMMENT 'Scarfcolor' ,
  SHOESCOLOR VARCHAR(10)   COMMENT 'Shoescolor' ,
  SHOESSTYLE VARCHAR(10)   COMMENT 'Shoesstyle' ,
  SKINCOLOR VARCHAR(255)   COMMENT 'Skincolor' ,
  SOURCEID VARCHAR(100)   COMMENT 'Sourceid' ,
  STATUS VARCHAR(10)   COMMENT 'Status' ,
  SUSPECTEDTERRORISTNUMBER VARCHAR(255)   COMMENT 'Suspectedterroristnumber' ,
  TARGETIMGURL VARCHAR(65535)   COMMENT 'Targetimgurl' ,
  TRACESERVICEINPUTTIME BIGINT   COMMENT 'Traceserviceinputtime' ,
  TRACETHINGSINPUTTIME BIGINT   COMMENT 'Tracethingsinputtime' ,
  TROUSERSCOLOR VARCHAR(10)   COMMENT 'Trouserscolor' ,
  TROUSERSCOLORRELIABILITY INTEGER   COMMENT 'Trouserscolorreliability' ,
  TROUSERSLEN VARCHAR(10)   COMMENT 'Trouserslen' ,
  TROUSERSLENRELIABILITY INTEGER   COMMENT 'Trouserslenreliability' ,
  TROUSERSSTYLE VARCHAR(10)   COMMENT 'Trousersstyle' ,
  UID VARCHAR(10)   COMMENT 'Uid' ,
  UMBRELLA INTEGER   COMMENT 'Umbrella' ,
  UMBRELLACOLOR VARCHAR(10)   COMMENT 'Umbrellacolor' ,
  UMBRELLARELIABILITY INTEGER   COMMENT 'Umbrellareliability' ,
  UNIFORMSTYLE INTEGER   COMMENT 'Uniformstyle' ,
  UNIFORMSTYLERELIABILITY INTEGER   COMMENT 'Uniformstylereliability' ,
  USEDNAME VARCHAR(255)   COMMENT 'Usedname' ,
  USERCHANNELCODE VARCHAR(100)   COMMENT 'Userchannelcode' ,
  VEHICLECOLOR VARCHAR(10)   COMMENT 'Vehiclecolor' ,
  VEHICLETYPE INTEGER   COMMENT 'Vehicletype' ,
  VEHICLETYPERELIABILITY INTEGER   COMMENT 'Vehicletypereliability' ,
  VENDOR VARCHAR(10)   COMMENT 'Vendor' ,
  VICTIMTYPE VARCHAR(255)   COMMENT 'Victimtype' ,
  constraint PK_DAHUA_NON_MOTOR_VEHICLE primary key (ABSSCORE)
);


      COMMENT ON TABLE DAHUA_CAMERA IS '大华设备表';
                
      COMMENT ON COLUMN DAHUA_CAMERA.ID IS '主键';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.DEVICE_ID IS '设备编号';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.NAME IS '设备名称';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.IP_ADDR IS '设备IP地址';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.PORT IS '端口号';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.USERNAME IS '用户名';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.PASSWORD IS '密码';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.ENABLE_STATUS IS '启用状态：1=启用，0=禁用';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.ONLINE_STATUS IS '在线状态：1=在线，0=离线';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.UPDATE_TIME IS '更新时间';
                    
      COMMENT ON TABLE DAHUA_NON_MOTOR_VEHICLE IS 'Dahuanonmotorvehicle';
                
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ABSSCORE IS 'Absscore';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ACCOMPANYNUMBER IS 'Accompanynumber';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ACCOMPANYNUMBERRELIABILITY IS 'Accompanynumberreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.AGE IS 'Age';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.AGEGROUP IS 'Agegroup';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.AGEGROUPRELIABILITY IS 'Agegroupreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.AGELOWERLIMIT IS 'Agelowerlimit';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.AGERELIABILITY IS 'Agereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.AGEUPLIMIT IS 'Ageuplimit';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ALGORITHMVERSION IS 'Algorithmversion';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ALIAS IS 'Alias';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.APPENDANT IS 'Appendant';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.APPENDANTDESCRIPTION IS 'Appendantdescription';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BABY IS 'Baby';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAG1RELIABILITY IS 'Bag1reliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAG1STYLE IS 'Bag1style';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAG2RELIABILITY IS 'Bag2reliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAG2STYLE IS 'Bag2style';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAG3RELIABILITY IS 'Bag3reliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAG3STYLE IS 'Bag3style';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAGCOLOR IS 'Bagcolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAGSTYLE IS 'Bagstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAGSTYLERELIABILITY IS 'Bagstylereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BEHAVIOR IS 'Behavior';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BEHAVIORDESCRIPTION IS 'Behaviordescription';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BODYFEATURE IS 'Bodyfeature';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BODYSPECIALLMARK IS 'Bodyspeciallmark';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BODYTYPE IS 'Bodytype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CACHEIMGURL IS 'Cacheimgurl';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CACHEPLATEIMGURL IS 'Cacheplateimgurl';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CACHETARGETIMGURL IS 'Cachetargetimgurl';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CAPCOLOR IS 'Capcolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CAPCOLORRELIABILITY IS 'Capcolorreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CAPSTYLE IS 'Capstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CAPSTYLERELIABILITY IS 'Capstylereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CAPTIME IS 'Captime';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CHANNELCODE IS 'Channelcode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CHANNELID IS 'Channelid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CHINESEACCENTCODE IS 'Chineseaccentcode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATCOLOR IS 'Coatcolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATCOLORRELIABILITY IS 'Coatcolorreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATLENGTH IS 'Coatlength';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATLENGTHRELIABILITY IS 'Coatlengthreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATSTYLE IS 'Coatstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATSTYLERELIABILITY IS 'Coatstylereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATTEXTURE IS 'Coattexture';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATTEXTURERELIABILITY IS 'Coattexturereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COMPLETESCORE IS 'Completescore';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CORPSECONDITIONCODE IS 'Corpseconditioncode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CRIMECHARACTERCODE IS 'Crimecharactercode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CRIMEMETHOD IS 'Crimemethod';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CRIMINALINVOLVEDCODE IS 'Criminalinvolvedcode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DATASOURCE IS 'Datasource';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DATATRACETAG IS 'Datatracetag';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DETAINEESIDENTITY IS 'Detaineesidentity';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DETAINEESSPECIALIDENTITY IS 'Detaineesspecialidentity';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DETECTOBJECT IS 'Detectobject';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DETECTIONSCORE IS 'Detectionscore';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DETENTIONHOUSECODE IS 'Detentionhousecode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DEVICECODE IS 'Devicecode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DEVICEID IS 'Deviceid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.EMCLASSTYPE IS 'Emclasstype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ESCAPEDCRIMINALNUMBER IS 'Escapedcriminalnumber';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.EVENT IS 'Event';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.EXTRECORDID IS 'Extrecordid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.EXTRECORDSOURCE IS 'Extrecordsource';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.EXTRACTEDFLAG IS 'Extractedflag';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.FACEDIRECT IS 'Facedirect';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.FACEDIRECTRELIABILITY IS 'Facedirectreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.FACESTYLE IS 'Facestyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.FACIALFEATURE IS 'Facialfeature';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.FEATUREDATA IS 'Featuredata';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.FEATUREID IS 'Featureid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.GENDER IS 'Gender';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.GENDERRELIABILITY IS 'Genderreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.GESTURE IS 'Gesture';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.GLASSCOLOR IS 'Glasscolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.GLASSSTYLE IS 'Glassstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HABITUALMOVEMEN IS 'Habitualmovemen';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HAIRCOLOR IS 'Haircolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HAIRSTYLE IS 'Hairstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HAIRSTYLERELIABILITY IS 'Hairstylereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HAIRTYPE IS 'Hairtype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASBAG IS 'Hasbag';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASBAGRELIABILITY IS 'Hasbagreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASBASKET IS 'Hasbasket';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASCARRIERBAG IS 'Hascarrierbag';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASCARRYSTUFF IS 'Hascarrystuff';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASCART IS 'Hascart';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASDOWNBODY IS 'Hasdownbody';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASDOWNBODYRELIABILITY IS 'Hasdownbodyreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASERRORDETECT IS 'Haserrordetect';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASHEAD IS 'Hashead';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASHEADRELIABILITY IS 'Hasheadreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASMIRROR IS 'Hasmirror';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASRAINCOAT IS 'Hasraincoat';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASRESPIRATOR IS 'Hasrespirator';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASTRUNK IS 'Hastrunk';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASVEHICLE IS 'Hasvehicle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASVEST IS 'Hasvest';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASVESTRELIABILITY IS 'Hasvestreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HAT IS 'Hat';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HATRELIABILITY IS 'Hatreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HEIGHTLOWERLIMIT IS 'Heightlowerlimit';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HEIGHTUPLIMIT IS 'Heightuplimit';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HUMANLIST IS 'Humanlist';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.IDNUMBER IS 'Idnumber';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.IDTYPE IS 'Idtype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.IMGHEIGHT IS 'Imgheight';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.IMGURL IS 'Imgurl';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.IMGWIDTH IS 'Imgwidth';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.IMMIGRANTTYPECODE IS 'Immigranttypecode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.INFOKIND IS 'Infokind';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.INJUREDDEGREE IS 'Injureddegree';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.IQASCORE IS 'Iqascore';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISCRIMINALINVOLVED IS 'Iscriminalinvolved';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISDETAINEES IS 'Isdetainees';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISDRIVER IS 'Isdriver';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISFOREIGNER IS 'Isforeigner';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISNONCOMPLETE IS 'Isnoncomplete';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISSUSPECTEDTERRORIST IS 'Issuspectedterrorist';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISSUSPICIOUSPERSON IS 'Issuspiciousperson';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISVICTIM IS 'Isvictim';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.JOBCATEGORY IS 'Jobcategory';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.LOCATIONMARKTIME IS 'Locationmarktime';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.MASK IS 'Mask';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.MASKCOLOR IS 'Maskcolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.MEMBERTYPECODE IS 'Membertypecode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.NAME IS 'Name';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.NATIONALITYCODE IS 'Nationalitycode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.NATIVECITYCODE IS 'Nativecitycode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.NONVEHICLEUMBRELLACOLOR IS 'Nonvehicleumbrellacolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.NONVEHICLEUMBRELLATYPE IS 'Nonvehicleumbrellatype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.NONVEHICLEUMBRELLATYPERELIABILITY IS 'Nonvehicleumbrellatypereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.OBJSIZE IS 'Objsize';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.OBJECTSUBTYPE IS 'Objectsubtype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PASSENGER IS 'Passenger';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PASSPORTTYPE IS 'Passporttype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONAPPEARTIME IS 'Personappeartime';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONBOTTOM IS 'Personbottom';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONDISAPPEARTIME IS 'Persondisappeartime';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONIMGID IS 'Personimgid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONLEFT IS 'Personleft';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONORG IS 'Personorg';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONRIGHT IS 'Personright';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONTOP IS 'Persontop';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PHYSICALFEATURE IS 'Physicalfeature';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PICRECORDID IS 'Picrecordid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PLATEBOTTOM IS 'Platebottom';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PLATECOLOR IS 'Platecolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PLATEIMGURL IS 'Plateimgurl';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PLATELEFT IS 'Plateleft';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PLATENUM IS 'Platenum';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PLATERIGHT IS 'Plateright';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PLATETOP IS 'Platetop';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.POSTURE IS 'Posture';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.POSTURERELIABILITY IS 'Posturereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PREVMSGRECORDID IS 'Prevmsgrecordid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.QESCORE IS 'Qescore';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RAINCOATRELIABILITY IS 'Raincoatreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RECORDID IS 'Recordid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RELATEDFACE IS 'Relatedface';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RELATEDGAIT IS 'Relatedgait';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RELATEDNONVEHICLE IS 'Relatednonvehicle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RELATEDNONVEHICLELIST IS 'Relatednonvehiclelist';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RELATEDPERSON IS 'Relatedperson';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RELIABLITY IS 'Reliablity';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RESIDENCEADMINDIVISION IS 'Residenceadmindivision';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RESPIRATORCOLOR IS 'Respiratorcolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RFIDINFO IS 'Rfidinfo';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RIDERVEHICLE IS 'Ridervehicle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.SNUMBER IS 'Snumber';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.SCARFCOLOR IS 'Scarfcolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.SHOESCOLOR IS 'Shoescolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.SHOESSTYLE IS 'Shoesstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.SKINCOLOR IS 'Skincolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.SOURCEID IS 'Sourceid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.STATUS IS 'Status';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.SUSPECTEDTERRORISTNUMBER IS 'Suspectedterroristnumber';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TARGETIMGURL IS 'Targetimgurl';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TRACESERVICEINPUTTIME IS 'Traceserviceinputtime';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TRACETHINGSINPUTTIME IS 'Tracethingsinputtime';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TROUSERSCOLOR IS 'Trouserscolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TROUSERSCOLORRELIABILITY IS 'Trouserscolorreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TROUSERSLEN IS 'Trouserslen';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TROUSERSLENRELIABILITY IS 'Trouserslenreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TROUSERSSTYLE IS 'Trousersstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.UID IS 'Uid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.UMBRELLA IS 'Umbrella';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.UMBRELLACOLOR IS 'Umbrellacolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.UMBRELLARELIABILITY IS 'Umbrellareliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.UNIFORMSTYLE IS 'Uniformstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.UNIFORMSTYLERELIABILITY IS 'Uniformstylereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.USEDNAME IS 'Usedname';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.USERCHANNELCODE IS 'Userchannelcode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.VEHICLECOLOR IS 'Vehiclecolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.VEHICLETYPE IS 'Vehicletype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.VEHICLETYPERELIABILITY IS 'Vehicletypereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.VENDOR IS 'Vendor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.VICTIMTYPE IS 'Victimtype';
                    
