
CREATE TABLE MOBILE_RESOURCE(
  ID VARCHAR2(20) NOT NULL ,
  PARENT_ID VARCHAR2(255)  ,
  TITLE VARCHAR2(255)  ,
  CODE VARCHAR2(255)  ,
  CATEGORY VARCHAR2(255)  ,
  MODULE VARCHAR2(255)  ,
  MENU_TYPE VARCHAR2(255)  ,
  PATH VARCHAR2(255)  ,
  ICON VARCHAR2(255)  ,
  COLOR VARCHAR2(255)  ,
  REG_TYPE VARCHAR2(255)  ,
  STATUS VARCHAR2(255)  ,
  SORT_CODE INTEGER  ,
  EXT_JSON CLOB  ,
  DELETE_FLAG VARCHAR2(255)  ,
  CREATE_TIME DATE  ,
  CREATE_USER VARCHAR2(20)  ,
  UPDATE_TIME DATE  ,
  UPDATE_USER VARCHAR2(20)  ,
  constraint PK_MOBILE_RESOURCE primary key (ID)
);


      COMMENT ON TABLE MOBILE_RESOURCE IS '移动资源';
                
      COMMENT ON COLUMN MOBILE_RESOURCE.ID IS '主键';
                    
      COMMENT ON COLUMN MOBILE_RESOURCE.PARENT_ID IS '父ID';
                    
      COMMENT ON COLUMN MOBILE_RESOURCE.TITLE IS '名称';
                    
      COMMENT ON COLUMN MOBILE_RESOURCE.CODE IS '编码';
                    
      COMMENT ON COLUMN MOBILE_RESOURCE.CATEGORY IS '分类';
                    
      COMMENT ON COLUMN MOBILE_RESOURCE.MODULE IS '模块';
                    
      COMMENT ON COLUMN MOBILE_RESOURCE.MENU_TYPE IS '菜单类型';
                    
      COMMENT ON COLUMN MOBILE_RESOURCE.PATH IS '路径';
                    
      COMMENT ON COLUMN MOBILE_RESOURCE.ICON IS '图标';
                    
      COMMENT ON COLUMN MOBILE_RESOURCE.COLOR IS '颜色';
                    
      COMMENT ON COLUMN MOBILE_RESOURCE.REG_TYPE IS '规则类型';
                    
      COMMENT ON COLUMN MOBILE_RESOURCE.STATUS IS '可用状态';
                    
      COMMENT ON COLUMN MOBILE_RESOURCE.SORT_CODE IS '排序码';
                    
      COMMENT ON COLUMN MOBILE_RESOURCE.EXT_JSON IS '扩展信息';
                    
      COMMENT ON COLUMN MOBILE_RESOURCE.DELETE_FLAG IS '删除标志';
                    
      COMMENT ON COLUMN MOBILE_RESOURCE.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN MOBILE_RESOURCE.CREATE_USER IS '创建用户';
                    
      COMMENT ON COLUMN MOBILE_RESOURCE.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON COLUMN MOBILE_RESOURCE.UPDATE_USER IS '修改用户';
                    
