
CREATE TABLE AUTH_THIRD_USER(
  ID VARCHAR(20) NOT NULL    COMMENT 'Id',
  THIRD_ID VARCHAR(255) NULL    COMMENT '三方用户id',
  USER_ID VARCHAR(20) NULL    COMMENT '系统用户id',
  AVATAR LONGTEXT NULL    COMMENT '头像',
  NAME VARCHAR(255) NULL    COMMENT '姓名',
  NICKNAME VARCHAR(255) NULL    COMMENT '昵称',
  GENDER VARCHAR(255) NULL    COMMENT '性别',
  CATEGORY VARCHAR(255) NULL    COMMENT '分类',
  EXT_JSON LONGTEXT NULL    COMMENT '扩展信息',
  DELETE_FLAG VARCHAR(255) NULL    COMMENT '删除标志',
  CREATE_TIME DATETIME NULL    COMMENT '创建时间',
  CREATE_USER VARCHAR(20) NULL    COMMENT '创建用户',
  UPDATE_TIME DATETIME NULL    COMMENT '修改时间',
  UPDATE_USER VARCHAR(20) NULL    COMMENT '修改用户',
  constraint PK_AUTH_THIRD_USER primary key (ID)
);


   ALTER TABLE AUTH_THIRD_USER COMMENT '三方用户';
                
