
CREATE TABLE MOBILE_RESOURCE(
  ID VARCHAR(20) NOT NULL    COMMENT '主键',
  PARENT_ID VARCHAR(255) NULL    COMMENT '父ID',
  TITLE VARCHAR(255) NULL    COMMENT '名称',
  CODE VARCHAR(255) NULL    COMMENT '编码',
  CATEGORY VARCHAR(255) NULL    COMMENT '分类',
  MODULE VARCHAR(255) NULL    COMMENT '模块',
  MENU_TYPE VARCHAR(255) NULL    COMMENT '菜单类型',
  PATH VARCHAR(255) NULL    COMMENT '路径',
  ICON VARCHAR(255) NULL    COMMENT '图标',
  COLOR VARCHAR(255) NULL    COMMENT '颜色',
  REG_TYPE VARCHAR(255) NULL    COMMENT '规则类型',
  STATUS VARCHAR(255) NULL    COMMENT '可用状态',
  SORT_CODE INTEGER NULL    COMMENT '排序码',
  EXT_JSON LONGTEXT NULL    COMMENT '扩展信息',
  DELETE_FLAG VARCHAR(255) NULL    COMMENT '删除标志',
  CREATE_TIME DATETIME NULL    COMMENT '创建时间',
  CREATE_USER VARCHAR(20) NULL    COMMENT '创建用户',
  UPDATE_TIME DATETIME NULL    COMMENT '修改时间',
  UPDATE_USER VARCHAR(20) NULL    COMMENT '修改用户',
  constraint PK_MOBILE_RESOURCE primary key (ID)
);


   ALTER TABLE MOBILE_RESOURCE COMMENT '移动资源';
                
