solon.app:
  name: fliad-gps001
  group: com.fliad

# 服务端口配置
server.port: 8080

# 数据源配置
solon.datasource.mysql:
  jdbcUrl: jdbc:mysql://10.20.10.7:3307/test?useSSL=false&serverTimezone=UTC
  username: root
  password: Root@2021
  driverClassName: com.mysql.cj.jdbc.Driver

# Doris数据源配置
solon.datasource.doris:
  jdbcUrl: jdbc:mysql://10.20.10.7:3307/test?useSSL=false&serverTimezone=UTC
  username: root
  password: Root@2021
  driverClassName: com.mysql.cj.jdbc.Driver

# GPS API配置
gps:
  api:
    lkyw:
      url: http://localhost:12009/jkfw/region/getyzlkywgps
      token: 8914dfc5-beca-45c9-918c-01791b9c8b62
    hc:
      url: http://localhost:12009/jkfw/region/getyzhcgps
      token: 8914dfc5-beca-45c9-918c-01791b9c8b62

# Kafka配置
kafka:
  bootstrap:
    servers: localhost:9092

#########################################
# logging configuration
#########################################
# # 以下为默认值，可以都不加，或者想改哪行加哪行(支持"云端配置服务"进行配置，支持写到"云端日志服务")
solon.logging.appender:
  console:
    level: TRACE
    enable: true #是否启用
  file:
    name: "logs/${solon.app.name}"
    level: INFO
    enable: true #是否启用
    extension: ".log"   #v2.2.18 后支持（例：.log, .log.gz, .log.zip）
    maxFileSize: "10 MB"
    maxHistory: "7"
  cloud:
    level: INFO
    enable: false #是否启用