<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.fliad</groupId>
        <artifactId>fliad-viid</artifactId>
        <version>0.1.0</version>
    </parent>

    <artifactId>fliad-common</artifactId>
    <packaging>jar</packaging>
    <description>基础通用模块</description>

    <dependencies>
        <!-- validation -->
        <dependency>
            <groupId>org.noear</groupId>
            <artifactId>solon.validation</artifactId>
        </dependency>

        <!-- web -->
        <dependency>
            <groupId>org.noear</groupId>
            <artifactId>solon-web</artifactId>
        </dependency>

        <!-- redis -->
        <!--<dependency>
            <groupId>org.noear</groupId>
            <artifactId>redisx</artifactId>
        </dependency>-->


        

        <!-- mybatis-flex -->
        <dependency>
            <groupId>com.mybatis-flex</groupId>
            <artifactId>mybatis-flex-solon-plugin</artifactId>
        </dependency>


        <!-- redis -->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-pool2</artifactId>
        </dependency>

        <!-- hutool -->
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
        </dependency>

        <!-- ip2region -->
        <dependency>
            <groupId>org.lionsoul</groupId>
            <artifactId>ip2region</artifactId>
        </dependency>

        <!-- knife4j -->
        <dependency>
            <groupId>org.noear</groupId>
            <artifactId>solon-swagger2-knife4j</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-core</artifactId>
            <version>${sa-token.version}</version>
        </dependency>

        <!-- junit Jupiter -->
        <dependency>
            <groupId>org.noear</groupId>
            <artifactId>solon-test-junit5</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.fliad</groupId>
            <artifactId>fliad-plugin-nop-report-core</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.fliad</groupId>
            <artifactId>fliad-plugin-nop-orm</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
