
CREATE TABLE DAHUA_CAMERA(
  ID NUMBER(20) NOT NULL ,
  DEVICE_ID VARCHAR2(64)  ,
  NAME VARCHAR2(128) NOT NULL ,
  IP_ADDR VARCHAR2(64) NOT NULL ,
  PORT INTEGER NOT NULL ,
  USERNAME VARCHAR2(64) NOT NULL ,
  PASSWORD VARCHAR2(128) NOT NULL ,
  ENABLE_STATUS INTEGER default 1  NOT NULL ,
  ONLINE_STATUS INTEGER default 0  NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint IDX_DAHUA_CAMERA_DEVICE_ID unique (DEVICE_ID),
  constraint IDX_DAHUA_CAMERA_NAME unique (NAME),
  constraint IDX_DAHUA_CAMERA_IP_ADDR unique (IP_ADDR),
  constraint PK_DAHUA_CAMERA primary key (ID)
);

CREATE TABLE DAHUA_NON_MOTOR_VEHICLE(
  ABSSCORE INTEGER  ,
  ACCOMPANYNUMBER INTEGER  ,
  ACCOMPANYNUMBERRELIABILITY INTEGER  ,
  AGE INTEGER  ,
  AGEGROUP INTEGER  ,
  AGEGROUPRELIABILITY INTEGER  ,
  AGELOWERLIMIT INTEGER  ,
  AGERELIABILITY INTEGER  ,
  AGEUPLIMIT INTEGER  ,
  ALGORITHMVERSION VARCHAR2(50)  ,
  ALIAS VARCHAR2(255)  ,
  APPENDANT VARCHAR2(10)  ,
  APPENDANTDESCRIPTION CLOB  ,
  BABY VARCHAR2(10)  ,
  BAG1RELIABILITY INTEGER  ,
  BAG1STYLE VARCHAR2(10)  ,
  BAG2RELIABILITY INTEGER  ,
  BAG2STYLE VARCHAR2(10)  ,
  BAG3RELIABILITY INTEGER  ,
  BAG3STYLE VARCHAR2(10)  ,
  BAGCOLOR VARCHAR2(10)  ,
  BAGSTYLE VARCHAR2(10)  ,
  BAGSTYLERELIABILITY INTEGER  ,
  BEHAVIOR CLOB  ,
  BEHAVIORDESCRIPTION CLOB  ,
  BODYFEATURE CLOB  ,
  BODYSPECIALLMARK CLOB  ,
  BODYTYPE VARCHAR2(255)  ,
  CACHEIMGURL CLOB  ,
  CACHEPLATEIMGURL CLOB  ,
  CACHETARGETIMGURL CLOB  ,
  CAPCOLOR VARCHAR2(10)  ,
  CAPCOLORRELIABILITY INTEGER  ,
  CAPSTYLE VARCHAR2(10)  ,
  CAPSTYLERELIABILITY INTEGER  ,
  CAPTIME NUMBER(20)  ,
  CHANNELCODE VARCHAR2(100)  ,
  CHANNELID VARCHAR2(100)  ,
  CHINESEACCENTCODE VARCHAR2(255)  ,
  COATCOLOR VARCHAR2(10)  ,
  COATCOLORRELIABILITY INTEGER  ,
  COATLENGTH VARCHAR2(10)  ,
  COATLENGTHRELIABILITY INTEGER  ,
  COATSTYLE VARCHAR2(10)  ,
  COATSTYLERELIABILITY INTEGER  ,
  COATTEXTURE VARCHAR2(10)  ,
  COATTEXTURERELIABILITY INTEGER  ,
  COMPLETESCORE INTEGER  ,
  CORPSECONDITIONCODE VARCHAR2(255)  ,
  CRIMECHARACTERCODE VARCHAR2(255)  ,
  CRIMEMETHOD CLOB  ,
  CRIMINALINVOLVEDCODE VARCHAR2(255)  ,
  DATASOURCE INTEGER  ,
  DATATRACETAG CLOB  ,
  DETAINEESIDENTITY VARCHAR2(255)  ,
  DETAINEESSPECIALIDENTITY VARCHAR2(255)  ,
  DETECTOBJECT INTEGER  ,
  DETECTIONSCORE INTEGER  ,
  DETENTIONHOUSECODE VARCHAR2(255)  ,
  DEVICECODE VARCHAR2(255)  ,
  DEVICEID VARCHAR2(100)  ,
  EMCLASSTYPE INTEGER  ,
  ESCAPEDCRIMINALNUMBER VARCHAR2(255)  ,
  EVENT VARCHAR2(50)  ,
  EXTRECORDID VARCHAR2(255)  ,
  EXTRECORDSOURCE INTEGER  ,
  EXTRACTEDFLAG INTEGER  ,
  FACEDIRECT INTEGER  ,
  FACEDIRECTRELIABILITY INTEGER  ,
  FACESTYLE VARCHAR2(255)  ,
  FACIALFEATURE CLOB  ,
  FEATUREDATA CLOB  ,
  FEATUREID VARCHAR2(100)  ,
  GENDER INTEGER  ,
  GENDERRELIABILITY INTEGER  ,
  GESTURE VARCHAR2(10)  ,
  GLASSCOLOR VARCHAR2(10)  ,
  GLASSSTYLE VARCHAR2(255)  ,
  HABITUALMOVEMEN VARCHAR2(10)  ,
  HAIRCOLOR VARCHAR2(255)  ,
  HAIRSTYLE VARCHAR2(10)  ,
  HAIRSTYLERELIABILITY INTEGER  ,
  HAIRTYPE INTEGER  ,
  HASBAG INTEGER  ,
  HASBAGRELIABILITY INTEGER  ,
  HASBASKET INTEGER  ,
  HASCARRIERBAG INTEGER  ,
  HASCARRYSTUFF INTEGER  ,
  HASCART INTEGER  ,
  HASDOWNBODY INTEGER  ,
  HASDOWNBODYRELIABILITY INTEGER  ,
  HASERRORDETECT INTEGER  ,
  HASHEAD INTEGER  ,
  HASHEADRELIABILITY INTEGER  ,
  HASMIRROR INTEGER  ,
  HASRAINCOAT INTEGER  ,
  HASRESPIRATOR INTEGER  ,
  HASTRUNK INTEGER  ,
  HASVEHICLE INTEGER  ,
  HASVEST INTEGER  ,
  HASVESTRELIABILITY INTEGER  ,
  HAT INTEGER  ,
  HATRELIABILITY INTEGER  ,
  HEIGHTLOWERLIMIT INTEGER  ,
  HEIGHTUPLIMIT INTEGER  ,
  HUMANLIST CLOB  ,
  IDNUMBER VARCHAR2(255)  ,
  IDTYPE VARCHAR2(255)  ,
  IMGHEIGHT INTEGER  ,
  IMGURL CLOB  ,
  IMGWIDTH INTEGER  ,
  IMMIGRANTTYPECODE VARCHAR2(255)  ,
  INFOKIND INTEGER  ,
  INJUREDDEGREE VARCHAR2(10)  ,
  IQASCORE INTEGER  ,
  ISCRIMINALINVOLVED INTEGER  ,
  ISDETAINEES INTEGER  ,
  ISDRIVER INTEGER  ,
  ISFOREIGNER INTEGER  ,
  ISNONCOMPLETE INTEGER  ,
  ISSUSPECTEDTERRORIST INTEGER  ,
  ISSUSPICIOUSPERSON INTEGER  ,
  ISVICTIM INTEGER  ,
  JOBCATEGORY VARCHAR2(255)  ,
  LOCATIONMARKTIME NUMBER(20)  ,
  MASK INTEGER  ,
  MASKCOLOR INTEGER  ,
  MEMBERTYPECODE VARCHAR2(255)  ,
  NAME VARCHAR2(255)  ,
  NATIONALITYCODE VARCHAR2(255)  ,
  NATIVECITYCODE VARCHAR2(255)  ,
  NONVEHICLEUMBRELLACOLOR VARCHAR2(10)  ,
  NONVEHICLEUMBRELLATYPE INTEGER  ,
  NONVEHICLEUMBRELLATYPERELIABILITY INTEGER  ,
  OBJSIZE INTEGER  ,
  OBJECTSUBTYPE INTEGER  ,
  PASSENGER INTEGER  ,
  PASSPORTTYPE VARCHAR2(255)  ,
  PERSONAPPEARTIME NUMBER(20)  ,
  PERSONBOTTOM INTEGER  ,
  PERSONDISAPPEARTIME NUMBER(20)  ,
  PERSONIMGID VARCHAR2(100)  ,
  PERSONLEFT INTEGER  ,
  PERSONORG VARCHAR2(255)  ,
  PERSONRIGHT INTEGER  ,
  PERSONTOP INTEGER  ,
  PHYSICALFEATURE CLOB  ,
  PICRECORDID VARCHAR2(100)  ,
  PLATEBOTTOM INTEGER  ,
  PLATECOLOR VARCHAR2(255)  ,
  PLATEIMGURL CLOB  ,
  PLATELEFT INTEGER  ,
  PLATENUM VARCHAR2(255)  ,
  PLATERIGHT INTEGER  ,
  PLATETOP INTEGER  ,
  POSTURE INTEGER  ,
  POSTURERELIABILITY INTEGER  ,
  PREVMSGRECORDID VARCHAR2(100)  ,
  QESCORE INTEGER  ,
  RAINCOATRELIABILITY INTEGER  ,
  RECORDID VARCHAR2(100)  ,
  RELATEDFACE INTEGER  ,
  RELATEDGAIT INTEGER  ,
  RELATEDNONVEHICLE INTEGER  ,
  RELATEDNONVEHICLELIST CLOB  ,
  RELATEDPERSON INTEGER  ,
  RELIABLITY INTEGER  ,
  RESIDENCEADMINDIVISION VARCHAR2(255)  ,
  RESPIRATORCOLOR VARCHAR2(10)  ,
  RFIDINFO CLOB  ,
  RIDERVEHICLE INTEGER  ,
  SNUMBER VARCHAR2(10)  ,
  SCARFCOLOR VARCHAR2(10)  ,
  SHOESCOLOR VARCHAR2(10)  ,
  SHOESSTYLE VARCHAR2(10)  ,
  SKINCOLOR VARCHAR2(255)  ,
  SOURCEID VARCHAR2(100)  ,
  STATUS VARCHAR2(10)  ,
  SUSPECTEDTERRORISTNUMBER VARCHAR2(255)  ,
  TARGETIMGURL CLOB  ,
  TRACESERVICEINPUTTIME NUMBER(20)  ,
  TRACETHINGSINPUTTIME NUMBER(20)  ,
  TROUSERSCOLOR VARCHAR2(10)  ,
  TROUSERSCOLORRELIABILITY INTEGER  ,
  TROUSERSLEN VARCHAR2(10)  ,
  TROUSERSLENRELIABILITY INTEGER  ,
  TROUSERSSTYLE VARCHAR2(10)  ,
  "UID" VARCHAR2(10)  ,
  UMBRELLA INTEGER  ,
  UMBRELLACOLOR VARCHAR2(10)  ,
  UMBRELLARELIABILITY INTEGER  ,
  UNIFORMSTYLE INTEGER  ,
  UNIFORMSTYLERELIABILITY INTEGER  ,
  USEDNAME VARCHAR2(255)  ,
  USERCHANNELCODE VARCHAR2(100)  ,
  VEHICLECOLOR VARCHAR2(10)  ,
  VEHICLETYPE INTEGER  ,
  VEHICLETYPERELIABILITY INTEGER  ,
  VENDOR VARCHAR2(10)  ,
  VICTIMTYPE VARCHAR2(255)  ,
  constraint PK_DAHUA_NON_MOTOR_VEHICLE primary key (ABSSCORE)
);


      COMMENT ON TABLE DAHUA_CAMERA IS '大华设备表';
                
      COMMENT ON COLUMN DAHUA_CAMERA.ID IS '主键';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.DEVICE_ID IS '设备编号';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.NAME IS '设备名称';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.IP_ADDR IS '设备IP地址';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.PORT IS '端口号';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.USERNAME IS '用户名';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.PASSWORD IS '密码';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.ENABLE_STATUS IS '启用状态：1=启用，0=禁用';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.ONLINE_STATUS IS '在线状态：1=在线，0=离线';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN DAHUA_CAMERA.UPDATE_TIME IS '更新时间';
                    
      COMMENT ON TABLE DAHUA_NON_MOTOR_VEHICLE IS 'Dahuanonmotorvehicle';
                
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ABSSCORE IS 'Absscore';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ACCOMPANYNUMBER IS 'Accompanynumber';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ACCOMPANYNUMBERRELIABILITY IS 'Accompanynumberreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.AGE IS 'Age';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.AGEGROUP IS 'Agegroup';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.AGEGROUPRELIABILITY IS 'Agegroupreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.AGELOWERLIMIT IS 'Agelowerlimit';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.AGERELIABILITY IS 'Agereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.AGEUPLIMIT IS 'Ageuplimit';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ALGORITHMVERSION IS 'Algorithmversion';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ALIAS IS 'Alias';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.APPENDANT IS 'Appendant';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.APPENDANTDESCRIPTION IS 'Appendantdescription';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BABY IS 'Baby';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAG1RELIABILITY IS 'Bag1reliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAG1STYLE IS 'Bag1style';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAG2RELIABILITY IS 'Bag2reliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAG2STYLE IS 'Bag2style';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAG3RELIABILITY IS 'Bag3reliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAG3STYLE IS 'Bag3style';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAGCOLOR IS 'Bagcolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAGSTYLE IS 'Bagstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BAGSTYLERELIABILITY IS 'Bagstylereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BEHAVIOR IS 'Behavior';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BEHAVIORDESCRIPTION IS 'Behaviordescription';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BODYFEATURE IS 'Bodyfeature';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BODYSPECIALLMARK IS 'Bodyspeciallmark';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.BODYTYPE IS 'Bodytype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CACHEIMGURL IS 'Cacheimgurl';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CACHEPLATEIMGURL IS 'Cacheplateimgurl';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CACHETARGETIMGURL IS 'Cachetargetimgurl';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CAPCOLOR IS 'Capcolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CAPCOLORRELIABILITY IS 'Capcolorreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CAPSTYLE IS 'Capstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CAPSTYLERELIABILITY IS 'Capstylereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CAPTIME IS 'Captime';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CHANNELCODE IS 'Channelcode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CHANNELID IS 'Channelid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CHINESEACCENTCODE IS 'Chineseaccentcode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATCOLOR IS 'Coatcolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATCOLORRELIABILITY IS 'Coatcolorreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATLENGTH IS 'Coatlength';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATLENGTHRELIABILITY IS 'Coatlengthreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATSTYLE IS 'Coatstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATSTYLERELIABILITY IS 'Coatstylereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATTEXTURE IS 'Coattexture';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COATTEXTURERELIABILITY IS 'Coattexturereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.COMPLETESCORE IS 'Completescore';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CORPSECONDITIONCODE IS 'Corpseconditioncode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CRIMECHARACTERCODE IS 'Crimecharactercode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CRIMEMETHOD IS 'Crimemethod';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.CRIMINALINVOLVEDCODE IS 'Criminalinvolvedcode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DATASOURCE IS 'Datasource';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DATATRACETAG IS 'Datatracetag';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DETAINEESIDENTITY IS 'Detaineesidentity';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DETAINEESSPECIALIDENTITY IS 'Detaineesspecialidentity';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DETECTOBJECT IS 'Detectobject';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DETECTIONSCORE IS 'Detectionscore';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DETENTIONHOUSECODE IS 'Detentionhousecode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DEVICECODE IS 'Devicecode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.DEVICEID IS 'Deviceid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.EMCLASSTYPE IS 'Emclasstype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ESCAPEDCRIMINALNUMBER IS 'Escapedcriminalnumber';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.EVENT IS 'Event';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.EXTRECORDID IS 'Extrecordid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.EXTRECORDSOURCE IS 'Extrecordsource';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.EXTRACTEDFLAG IS 'Extractedflag';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.FACEDIRECT IS 'Facedirect';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.FACEDIRECTRELIABILITY IS 'Facedirectreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.FACESTYLE IS 'Facestyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.FACIALFEATURE IS 'Facialfeature';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.FEATUREDATA IS 'Featuredata';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.FEATUREID IS 'Featureid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.GENDER IS 'Gender';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.GENDERRELIABILITY IS 'Genderreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.GESTURE IS 'Gesture';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.GLASSCOLOR IS 'Glasscolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.GLASSSTYLE IS 'Glassstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HABITUALMOVEMEN IS 'Habitualmovemen';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HAIRCOLOR IS 'Haircolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HAIRSTYLE IS 'Hairstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HAIRSTYLERELIABILITY IS 'Hairstylereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HAIRTYPE IS 'Hairtype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASBAG IS 'Hasbag';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASBAGRELIABILITY IS 'Hasbagreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASBASKET IS 'Hasbasket';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASCARRIERBAG IS 'Hascarrierbag';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASCARRYSTUFF IS 'Hascarrystuff';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASCART IS 'Hascart';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASDOWNBODY IS 'Hasdownbody';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASDOWNBODYRELIABILITY IS 'Hasdownbodyreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASERRORDETECT IS 'Haserrordetect';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASHEAD IS 'Hashead';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASHEADRELIABILITY IS 'Hasheadreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASMIRROR IS 'Hasmirror';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASRAINCOAT IS 'Hasraincoat';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASRESPIRATOR IS 'Hasrespirator';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASTRUNK IS 'Hastrunk';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASVEHICLE IS 'Hasvehicle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASVEST IS 'Hasvest';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HASVESTRELIABILITY IS 'Hasvestreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HAT IS 'Hat';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HATRELIABILITY IS 'Hatreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HEIGHTLOWERLIMIT IS 'Heightlowerlimit';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HEIGHTUPLIMIT IS 'Heightuplimit';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.HUMANLIST IS 'Humanlist';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.IDNUMBER IS 'Idnumber';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.IDTYPE IS 'Idtype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.IMGHEIGHT IS 'Imgheight';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.IMGURL IS 'Imgurl';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.IMGWIDTH IS 'Imgwidth';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.IMMIGRANTTYPECODE IS 'Immigranttypecode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.INFOKIND IS 'Infokind';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.INJUREDDEGREE IS 'Injureddegree';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.IQASCORE IS 'Iqascore';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISCRIMINALINVOLVED IS 'Iscriminalinvolved';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISDETAINEES IS 'Isdetainees';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISDRIVER IS 'Isdriver';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISFOREIGNER IS 'Isforeigner';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISNONCOMPLETE IS 'Isnoncomplete';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISSUSPECTEDTERRORIST IS 'Issuspectedterrorist';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISSUSPICIOUSPERSON IS 'Issuspiciousperson';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.ISVICTIM IS 'Isvictim';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.JOBCATEGORY IS 'Jobcategory';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.LOCATIONMARKTIME IS 'Locationmarktime';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.MASK IS 'Mask';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.MASKCOLOR IS 'Maskcolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.MEMBERTYPECODE IS 'Membertypecode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.NAME IS 'Name';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.NATIONALITYCODE IS 'Nationalitycode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.NATIVECITYCODE IS 'Nativecitycode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.NONVEHICLEUMBRELLACOLOR IS 'Nonvehicleumbrellacolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.NONVEHICLEUMBRELLATYPE IS 'Nonvehicleumbrellatype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.NONVEHICLEUMBRELLATYPERELIABILITY IS 'Nonvehicleumbrellatypereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.OBJSIZE IS 'Objsize';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.OBJECTSUBTYPE IS 'Objectsubtype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PASSENGER IS 'Passenger';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PASSPORTTYPE IS 'Passporttype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONAPPEARTIME IS 'Personappeartime';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONBOTTOM IS 'Personbottom';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONDISAPPEARTIME IS 'Persondisappeartime';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONIMGID IS 'Personimgid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONLEFT IS 'Personleft';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONORG IS 'Personorg';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONRIGHT IS 'Personright';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PERSONTOP IS 'Persontop';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PHYSICALFEATURE IS 'Physicalfeature';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PICRECORDID IS 'Picrecordid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PLATEBOTTOM IS 'Platebottom';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PLATECOLOR IS 'Platecolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PLATEIMGURL IS 'Plateimgurl';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PLATELEFT IS 'Plateleft';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PLATENUM IS 'Platenum';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PLATERIGHT IS 'Plateright';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PLATETOP IS 'Platetop';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.POSTURE IS 'Posture';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.POSTURERELIABILITY IS 'Posturereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.PREVMSGRECORDID IS 'Prevmsgrecordid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.QESCORE IS 'Qescore';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RAINCOATRELIABILITY IS 'Raincoatreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RECORDID IS 'Recordid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RELATEDFACE IS 'Relatedface';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RELATEDGAIT IS 'Relatedgait';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RELATEDNONVEHICLE IS 'Relatednonvehicle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RELATEDNONVEHICLELIST IS 'Relatednonvehiclelist';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RELATEDPERSON IS 'Relatedperson';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RELIABLITY IS 'Reliablity';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RESIDENCEADMINDIVISION IS 'Residenceadmindivision';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RESPIRATORCOLOR IS 'Respiratorcolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RFIDINFO IS 'Rfidinfo';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.RIDERVEHICLE IS 'Ridervehicle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.SNUMBER IS 'Snumber';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.SCARFCOLOR IS 'Scarfcolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.SHOESCOLOR IS 'Shoescolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.SHOESSTYLE IS 'Shoesstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.SKINCOLOR IS 'Skincolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.SOURCEID IS 'Sourceid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.STATUS IS 'Status';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.SUSPECTEDTERRORISTNUMBER IS 'Suspectedterroristnumber';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TARGETIMGURL IS 'Targetimgurl';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TRACESERVICEINPUTTIME IS 'Traceserviceinputtime';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TRACETHINGSINPUTTIME IS 'Tracethingsinputtime';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TROUSERSCOLOR IS 'Trouserscolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TROUSERSCOLORRELIABILITY IS 'Trouserscolorreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TROUSERSLEN IS 'Trouserslen';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TROUSERSLENRELIABILITY IS 'Trouserslenreliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.TROUSERSSTYLE IS 'Trousersstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE."UID" IS 'Uid';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.UMBRELLA IS 'Umbrella';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.UMBRELLACOLOR IS 'Umbrellacolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.UMBRELLARELIABILITY IS 'Umbrellareliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.UNIFORMSTYLE IS 'Uniformstyle';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.UNIFORMSTYLERELIABILITY IS 'Uniformstylereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.USEDNAME IS 'Usedname';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.USERCHANNELCODE IS 'Userchannelcode';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.VEHICLECOLOR IS 'Vehiclecolor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.VEHICLETYPE IS 'Vehicletype';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.VEHICLETYPERELIABILITY IS 'Vehicletypereliability';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.VENDOR IS 'Vendor';
                    
      COMMENT ON COLUMN DAHUA_NON_MOTOR_VEHICLE.VICTIMTYPE IS 'Victimtype';
                    
