
CREATE TABLE sys_group(
  ID VARCHAR(50) NOT NULL    COMMENT '主键',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  REMARK VARCHAR(500) NULL    COMMENT '备注',
  SORT_CODE INTEGER NULL    COMMENT '排序码',
  EXT_JSON LONGTEXT NULL    COMMENT '扩展信息',
  DELETE_FLAG VARCHAR(255) NULL    COMMENT '删除标志',
  CREATE_TIME DATETIME NULL    COMMENT '创建时间',
  CREATE_USER VARCHAR(20) NULL    COMMENT '创建用户',
  UPDATE_TIME DATETIME NULL    COMMENT '修改时间',
  UPDATE_USER VARCHAR(20) NULL    COMMENT '修改用户',
  constraint PK_sys_group primary key (ID)
);

CREATE TABLE sys_org(
  ID VARCHAR(20) NOT NULL    COMMENT 'Id',
  PARENT_ID VARCHAR(20) NULL    COMMENT '父id',
  DIRECTOR_ID VARCHAR(20) NULL    COMMENT '主管ID',
  NAME VARCHAR(255) NULL    COMMENT '名称',
  CODE VARCHAR(255) NULL    COMMENT '编码',
  CATEGORY VARCHAR(255) NULL    COMMENT '分类',
  SORT_CODE INTEGER NULL    COMMENT '排序码',
  EXT_JSON LONGTEXT NULL    COMMENT '扩展信息',
  DELETE_FLAG VARCHAR(255) NULL    COMMENT '删除标志',
  CREATE_TIME DATETIME NULL    COMMENT '创建时间',
  CREATE_USER VARCHAR(20) NULL    COMMENT '创建用户',
  UPDATE_TIME DATETIME NULL    COMMENT '修改时间',
  UPDATE_USER VARCHAR(20) NULL    COMMENT '修改用户',
  constraint PK_sys_org primary key (ID)
);

CREATE TABLE sys_position(
  ID VARCHAR(20) NOT NULL    COMMENT 'Id',
  ORG_ID VARCHAR(20) NULL    COMMENT '组织id',
  NAME VARCHAR(255) NULL    COMMENT '名称',
  CODE VARCHAR(255) NULL    COMMENT '编码',
  CATEGORY VARCHAR(255) NULL    COMMENT '分类',
  SORT_CODE INTEGER NULL    COMMENT '排序码',
  EXT_JSON LONGTEXT NULL    COMMENT '扩展信息',
  DELETE_FLAG VARCHAR(255) NULL    COMMENT '删除标志',
  CREATE_TIME DATETIME NULL    COMMENT '创建时间',
  CREATE_USER VARCHAR(20) NULL    COMMENT '创建用户',
  UPDATE_TIME DATETIME NULL    COMMENT '修改时间',
  UPDATE_USER VARCHAR(20) NULL    COMMENT '修改用户',
  constraint PK_sys_position primary key (ID)
);

CREATE TABLE sys_relation(
  ID VARCHAR(20) NOT NULL    COMMENT 'Id',
  OBJECT_ID VARCHAR(255) NULL    COMMENT '对象ID',
  TARGET_ID VARCHAR(255) NULL    COMMENT '目标ID',
  CATEGORY VARCHAR(255) NULL    COMMENT '分类',
  EXT_JSON LONGTEXT NULL    COMMENT '扩展信息',
  constraint PK_sys_relation primary key (ID)
);

CREATE TABLE sys_resource(
  ID VARCHAR(20) NOT NULL    COMMENT 'Id',
  PARENT_ID VARCHAR(255) NULL    COMMENT '父id',
  TITLE VARCHAR(255) NULL    COMMENT '标题',
  NAME VARCHAR(255) NULL    COMMENT '别名',
  CODE VARCHAR(255) NULL    COMMENT '编码',
  CATEGORY VARCHAR(255) NULL    COMMENT '分类',
  MODULE VARCHAR(255) NULL    COMMENT '模块',
  MENU_TYPE VARCHAR(255) NULL    COMMENT '菜单类型',
  PATH TEXT NULL    COMMENT '路径',
  COMPONENT VARCHAR(255) NULL    COMMENT '组件',
  ICON VARCHAR(255) NULL    COMMENT '图标',
  COLOR VARCHAR(255) NULL    COMMENT '颜色',
  VISIBLE VARCHAR(255) NULL    COMMENT '是否可见',
  SORT_CODE INTEGER NULL    COMMENT '排序码',
  EXT_JSON LONGTEXT NULL    COMMENT '扩展信息',
  DELETE_FLAG VARCHAR(255) NULL    COMMENT '删除标志',
  CREATE_TIME DATETIME NULL    COMMENT '创建时间',
  CREATE_USER VARCHAR(20) NULL    COMMENT '创建用户',
  UPDATE_TIME DATETIME NULL    COMMENT '修改时间',
  UPDATE_USER VARCHAR(20) NULL    COMMENT '修改用户',
  constraint PK_sys_resource primary key (ID)
);

CREATE TABLE sys_role(
  ID VARCHAR(20) NOT NULL    COMMENT 'Id',
  ORG_ID VARCHAR(20) NULL    COMMENT '组织id',
  NAME VARCHAR(255) NULL    COMMENT '名称',
  CODE VARCHAR(255) NULL    COMMENT '编码',
  CATEGORY VARCHAR(255) NULL    COMMENT '分类',
  SORT_CODE INTEGER NULL    COMMENT '排序码',
  EXT_JSON LONGTEXT NULL    COMMENT '扩展信息',
  DELETE_FLAG VARCHAR(255) NULL    COMMENT '删除标志',
  CREATE_TIME DATETIME NULL    COMMENT '创建时间',
  CREATE_USER VARCHAR(20) NULL    COMMENT '创建用户',
  UPDATE_TIME DATETIME NULL    COMMENT '修改时间',
  UPDATE_USER VARCHAR(20) NULL    COMMENT '修改用户',
  constraint PK_sys_role primary key (ID)
);

CREATE TABLE sys_user(
  ID VARCHAR(20) NOT NULL    COMMENT 'Id',
  AVATAR LONGTEXT NULL    COMMENT '头像',
  SIGNATURE LONGTEXT NULL    COMMENT '签名',
  ACCOUNT VARCHAR(255) NULL    COMMENT '账号',
  PASSWORD VARCHAR(255) NULL    COMMENT '密码',
  NAME VARCHAR(255) NULL    COMMENT '姓名',
  NICKNAME VARCHAR(255) NULL    COMMENT '昵称',
  GENDER VARCHAR(255) NULL    COMMENT '性别',
  AGE VARCHAR(255) NULL    COMMENT '年龄',
  BIRTHDAY VARCHAR(255) NULL    COMMENT '出生日期',
  NATION VARCHAR(255) NULL    COMMENT '民族',
  NATIVE_PLACE VARCHAR(255) NULL    COMMENT '籍贯',
  HOME_ADDRESS TEXT NULL    COMMENT '家庭住址',
  MAILING_ADDRESS TEXT NULL    COMMENT '通信地址',
  ID_CARD_TYPE VARCHAR(255) NULL    COMMENT '证件类型',
  ID_CARD_NUMBER VARCHAR(255) NULL    COMMENT '证件号码',
  CULTURE_LEVEL VARCHAR(255) NULL    COMMENT '文化程度',
  POLITICAL_OUTLOOK VARCHAR(255) NULL    COMMENT '政治面貌',
  COLLEGE VARCHAR(255) NULL    COMMENT '毕业院校',
  EDUCATION VARCHAR(255) NULL    COMMENT '学历',
  EDU_LENGTH VARCHAR(255) NULL    COMMENT '学制',
  DEGREE VARCHAR(255) NULL    COMMENT '学位',
  PHONE VARCHAR(255) NULL    COMMENT '手机',
  EMAIL VARCHAR(255) NULL    COMMENT '邮箱',
  HOME_TEL VARCHAR(255) NULL    COMMENT '家庭电话',
  OFFICE_TEL VARCHAR(255) NULL    COMMENT '办公电话',
  EMERGENCY_CONTACT VARCHAR(255) NULL    COMMENT '紧急联系人',
  EMERGENCY_PHONE VARCHAR(255) NULL    COMMENT '紧急联系人电话',
  EMERGENCY_ADDRESS TEXT NULL    COMMENT '紧急联系人地址',
  EMP_NO VARCHAR(255) NULL    COMMENT '员工编号',
  ENTRY_DATE VARCHAR(255) NULL    COMMENT '入职日期',
  ORG_ID VARCHAR(20) NULL    COMMENT '机构id',
  POSITION_ID VARCHAR(20) NULL    COMMENT '职位id',
  POSITION_LEVEL VARCHAR(255) NULL    COMMENT '职级',
  DIRECTOR_ID VARCHAR(20) NULL    COMMENT '主管id',
  POSITION_JSON LONGTEXT NULL    COMMENT '兼任信息',
  LAST_LOGIN_IP VARCHAR(255) NULL    COMMENT '上次登录ip',
  LAST_LOGIN_ADDRESS VARCHAR(255) NULL    COMMENT '上次登录地点',
  LAST_LOGIN_TIME DATETIME NULL    COMMENT '上次登录时间',
  LAST_LOGIN_DEVICE TEXT NULL    COMMENT '上次登录设备',
  LATEST_LOGIN_IP VARCHAR(255) NULL    COMMENT '最新登录ip',
  LATEST_LOGIN_ADDRESS VARCHAR(255) NULL    COMMENT '最新登录地点',
  LATEST_LOGIN_TIME DATETIME NULL    COMMENT '最新登录时间',
  LATEST_LOGIN_DEVICE TEXT NULL    COMMENT '最新登录设备',
  USER_STATUS VARCHAR(255) NULL    COMMENT '用户状态',
  SORT_CODE INTEGER NULL    COMMENT '排序码',
  EXT_JSON LONGTEXT NULL    COMMENT '扩展信息',
  DELETE_FLAG VARCHAR(255) NULL    COMMENT '删除标志',
  CREATE_TIME DATETIME NULL    COMMENT '创建时间',
  CREATE_USER VARCHAR(20) NULL    COMMENT '创建用户',
  UPDATE_TIME DATETIME NULL    COMMENT '修改时间',
  UPDATE_USER VARCHAR(20) NULL    COMMENT '修改用户',
  constraint PK_sys_user primary key (ID)
);


   ALTER TABLE sys_group COMMENT '用户组';
                
   ALTER TABLE sys_org COMMENT '组织';
                
   ALTER TABLE sys_position COMMENT '职位';
                
   ALTER TABLE sys_relation COMMENT '关系';
                
   ALTER TABLE sys_resource COMMENT '资源';
                
   ALTER TABLE sys_role COMMENT '角色';
                
   ALTER TABLE sys_user COMMENT '用户';
                
