# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build windows native image1

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*' ]  # 只在推送 v 开头的标签时触发（例如 v1.0.0）
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:

      # 缓存Maven的本地仓库
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - uses: actions/checkout@v3 # 这是GitHub提供的一个动作（action），用于将代码从GitHub仓库检出到工作目录中。v3是该动作的版本号。
      - name: GitHub Action for GraalVM JDK 25
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25' # for a specific JDK 25;
          distribution: 'graalvm' # New 'distribution' option
          cache: maven

      - name: setup node v22.17.0
        uses: actions/setup-node@v3
        with:
          node-version: 22.17.0

      # 缓存前端构建产物
      - name: Cache frontend build1
        id: cache-frontend
        uses: actions/cache@v3
        with:
          path: ./fliad-admin-web/dist
          key: frontend-dist-${{ hashFiles('fliad-admin-web/package-lock.json') }}-${{ hashFiles('fliad-admin-web/src/**/*') }}

      - name: build fliad-admin-web
        if: steps.cache-frontend.outputs.cache-hit != 'true'
        run: |
          cd fliad-admin-web
          npm install
          npm run build

      - name: Build with Maven
        run: |
          set MAVEN_OPTS="-Duser.language=UTF-8 -Dfile.encoding=UTF-8"
          mvn clean package -P non-jdk8 -DskipTests --file pom.xml --no-transfer-progress

      - name: Build with Native Image
        run: |
          set MAVEN_OPTS="-Duser.language=UTF-8 -Dfile.encoding=UTF-8"
          cd fliad-web-app
          native-image -jar target/fliad-web-app.jar

      - name: copy resource
        run: |
          cp -r ./fliad-admin-web/dist/ ./package/fliad-web-app-native/fliad-admin-web/dist
          cp ./fliad-web-app/target/fliad-web-app.exe ./package/fliad-web-app-native/fliad-web-app.exe
          cp ./fliad-web-app/target/classes/app-local.yml ./package/fliad-web-app-native/app-local.yml
          cp ./fliad-web-app/target/*.dll ./package/fliad-web-app-native/
          
          cp -r ./fliad-admin-web/dist/ ./package/fliad-web-app/fliad-admin-web/dist
          cp ./fliad-web-app/target/*.jar ./package/fliad-web-app/
          cp ./fliad-web-app/target/classes/app-local.yml ./package/fliad-web-app/app-local.yml
          cp -r ./fliad-web-app/target/classes/_sql/ ./package/fliad-web-app/_sql

      - name: Upload artifacts app
        uses: actions/upload-artifact@v4
        with:
          name: fliad-web-app
          path: package/fliad-web-app
          if-no-files-found: error # 如果未找到文件，则报错

      - name: Upload artifacts app native
        uses: actions/upload-artifact@v4
        with:
          name: fliad-web-app-windows-native
          path: package/fliad-web-app-native
          if-no-files-found: error # 如果未找到文件，则报错

      - name: Compress target directory
        if: startsWith(github.ref, 'refs/tags/')  # 仅在标签推送时执行
        run: |
          Compress-Archive -Path "package/fliad-web-app/*" -DestinationPath "fliad-web-app.zip" -Force
          Compress-Archive -Path "package/fliad-web-app-native/*" -DestinationPath "fliad-web-app-windows-native.zip" -Force

      - name: Create Release and Attach Artifact
        if: startsWith(github.ref, 'refs/tags/')  # 仅在标签推送时执行
        uses: softprops/action-gh-release@v2
        with:
          files: |
            fliad-web-app.zip
            fliad-web-app-windows-native.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}


    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
