
CREATE TABLE BIZ_NOTICE(
  ID VARCHAR(20) NOT NULL    COMMENT '主键',
  TITLE VARCHAR(200) NULL    COMMENT '标题',
  IMAGE VARCHAR(200) NULL    COMMENT '封面图',
  CONTENT TEXT NULL    COMMENT '内容',
  DIGEST VARCHAR(300) NULL    COMMENT '摘要',
  TYPE VARCHAR(50) NULL    COMMENT '类型',
  PLACE VARCHAR(50) NULL    COMMENT '发布位置',
  STATUS VARCHAR(10) NULL    COMMENT '状态',
  SORT_CODE INTEGER NULL    COMMENT '排序',
  REMARK VARCHAR(500) NULL    COMMENT '备注',
  EXT_JSON LONGTEXT NULL    COMMENT '扩展信息',
  DELETE_FLAG VARCHAR(255) NULL    COMMENT '删除标志',
  CREATE_TIME DATETIME NULL    COMMENT '创建时间',
  CREATE_USER VARCHAR(20) NULL    COMMENT '创建用户',
  UPDATE_TIME DATETIME NULL    COMMENT '更新时间',
  UPDATE_USER VARCHAR(20) NULL    COMMENT '更新用户',
  constraint PK_BIZ_NOTICE primary key (ID)
);


   ALTER TABLE BIZ_NOTICE COMMENT '通知公告';
                
